### ISSUE TITLE
Current version different from what is published in "A graph-based approach to diploid genome assembly"

### ISSUE THREAD

**Issue by haghshenas** [whatshap/whatshap#1]
Hi,
Based on the [recommended workflow](https://whatshap.readthedocs.io/en/latest/guide.html#recommended-workflow) in the user guide, whatshap expects to be fed with variants called using FreeBayes. This looks different from what is published in the paper titled ["A graph-based approach to diploid genome assembly"](https://academic.oup.com/bioinformatics/article/34/13/i105/5045759).

Could you please tell me how I can run the software that is mentioned in the paper?

**Comment by tobiasmarschall** [comment]
It is presently living in this branch: https://bitbucket.org/whatshap/whatshap/branch/MAV-tobias

We hope to be able merge this soon and to include it in WhatsHap releases.

**Comment by haghshenas** [comment]
I see. Thanks for the response.
I look forward to see the release and the documentation.

**Comment by xiekunwhy** [comment]
Hi, @tobiasmarschall 
I could't find any instruction about how to use whatshap to assemble a genome, would you please add some. 
Best wishes,
Kun
