### ISSUE TITLE
The fasta sequence does not match the REF allele

### ISSUE THREAD

**Issue by marcelm** [whatshap/whatshap#195]
**[Original report](https://bitbucket.org/whatshap/whatshap/issue/195) by Alessandro (Bitbucket: [aderzell](https://bitbucket.org/aderzell), ).**

----------------------------------------

Hello,
after having run whatshap, I am unable to write the phased fasta files
```
whatshap phase --indels --ignore-read-groups --reference final.genome.scf.fasta -o phased.vcf arc.vcf ont.sorted.bam
bgzip phased.vcf
tabix phased.vcf.gz
bcftools consensus -H 1 -f final.genome.scf.fasta phased.vcf.gz > haplotype1.fasta
```
And I am getting the following error

```
The fasta sequence does not match the REF allele at scf7180000001096:1370420:
   .vcf: [C]
   .vcf: [CG] <- (ALT)
   .fa:  [G]GCCAGCTCTTCCACATCAATTCGACGACTACATCAATCCACAAC

```
If I am understanding well, my reference contains a G where the 2 phased haplotypes would be C and CG?

Could this come from the use of the --indels tag? That seems like a coordinate problem but that's just a guess.

**Comment by desa-la** [comment]
Hi @marcelm, sorry I am waking up this closed issue, but I am dealing with exactly same thing except I am not dealing with multi-allelic variants.
`The fasta sequence does not match the REF allele at Qrob_Chr02:16605162:
   .vcf: [C]
   .vcf: [A] <- (ALT)
   .fa:  [G]TTTAGGCTTTTTGGAACAATTGGTAATTT`
fasta goes on, I just cut it off for space.
Indeed my reference allele in my vcf file is C and not G as in fasta file. I just wonder how can this be, could removing indels in filtering step messed with coordinates and now I can't get haplotype consensus?

**Comment by marcelm** [comment]
Hi, this isn’t directly a WhatsHap issue, so I don’t think I can help much. One thing I can say is that WhatsHap 2.0 enables indel phasing by default. If you filter out indels anyway, you could try using `whatshap phase --only-snvs` to not phase indels. Maybe that gets rid of the error message, but your phasing won’t be as good of course.

If your VCF filtering just omits some variants and leaves the others untouched, then the coordinates should be fine.

**Comment by desa-la** [comment]
@marcelm Thank you for your quick response. Yes, filtering should just omit variants, so I am not sure what the issue could be, but as you pointed out it is not really a WhatsHap issue. Thank you for responding anyways:)
