### ISSUE TITLE
No error message for missing vcf index

### ISSUE THREAD

**Issue by marcelm** [whatshap/whatshap#196]
**[Original report](https://bitbucket.org/whatshap/whatshap/issue/196) by Nathan Olson (Bitbucket: [natedolson](https://bitbucket.org/natedolson), GitHub: [natedolson](https://github.com/natedolson)).**

----------------------------------------

Error was encountered using version 0.19.dev43\+g6e4097a

While using WhatHap to phase the HG002 ONT ultra-long reads I ran into an issue, specifically my input VCF file was not indexed. I know the documentation states that the input VCF file should be indexed so this is more an error on my part than WhatsHap. However, without an indexed VCF WhatsHap runs without detecting any variants for the chromosomes and as expected is unable to tag any of the reads, though without any error or warning messages. I was thinking adding an error or warning message when the index file is missing might be helpful for users like myself 😉.

**Comment by aalsabag** [comment]
I think this can be closed with this commit @natedolson

https://github.com/whatshap/whatshap/commit/f07bf36e95f5b3eb87598edf50dad9fa719e43c2

**Comment by tobiasmarschall** [comment]
Thanks @aalsabag. Closing this now.
