### ISSUE TITLE
Dev install error OSX Mojave

### ISSUE THREAD

**Issue by marcelm** [whatshap/whatshap#201]
**[Original report](https://bitbucket.org/whatshap/whatshap/issue/201) by Nathan Olson (Bitbucket: [natedolson](https://bitbucket.org/natedolson), GitHub: [natedolson](https://github.com/natedolson)).**

----------------------------------------

Installing dev version following the instructions on the whatshap homepage \([https://whatshap.readthedocs.io/en/latest/installation.html](https://whatshap.readthedocs.io/en/latest/installation.html)\), I get the following fatal error `whatshap/core.cpp:665:10: fatal error: 'ios' file not found`. From a quick google search I found a quick work around here, [https://github.com/huggingface/neuralcoref/issues/97](https://github.com/huggingface/neuralcoref/issues/97). Using the following to install the dev version, `CFLAGS='-stdlib=libc++' whatshap-env/bin/pip install git+https://bitbucket.org/whatshap/whatshap`. Full install log is attached.

**Comment by marcelm** [comment]
I let GitHub actions test the installation on macOS and it worked fine even without any patches, see <https://github.com/whatshap/whatshap/runs/836826256>. So I have a hard time reproducing this. I’m inclined to close this unless someone can help us find out what the problem is and how to solve it. I have re-based the `macos` branch for anyone who wants to start from there.

Otherwise, there is always the Bioconda package. We’re also planning to do more frequent releases, so it may not be as necessary to install the development version anymore.

**Comment by erikvdp** [comment]
I can confirm that the installation works fine on macOS, using the steps outlined in the documentation.

**Comment by marcelm** [comment]
Thanks for the feedback! I have now setup a monthly job that tests WhatsHap on macOS, so hopefully it will also keep working in the future.
