### ISSUE TITLE
Recomendation about 10x Genomics

### ISSUE THREAD

**Issue by marcelm** [whatshap/whatshap#228]
**[Original report](https://bitbucket.org/whatshap/whatshap/issue/228) by Pedro Almeida (Bitbucket: [Pedro Almeida](https://bitbucket.org/Pedro Almeida), ).**

----------------------------------------

Hi,

‌

I have a set of samples sequenced with 10x Genomics for which I ran the full Long Ranger pipeline. This effectively produces a phased BAM file \(with all the barcode and phasing tags\) and a phased VCF for each sample individually. I also genotyped these samples together with Freebayes \(multisample/joint calling\) using the Long Ranger BAM file and was thinking in incorporating the phase information of each sample into this multisample VCF file created by freebayes.

‌

It seems that WhatsHap can use 10x phasing information, but it was not clear to me whether it can use it in the `phase` stage or only in the `haplotag` stage. If the phasing tags from the Long Ranger BAM file are not supported for phasing the multisample VCF file in WhatsHap, would it be appropriate to use the phased, single-sample VCF as described in the manual [here](https://whatshap.readthedocs.io/en/latest/guide.html#using-a-phased-vcf-instead-of-a-bam-cram-file)? The problem I’m seing with this approach is that it is very likely that some variants that are in the phased single-sample VCF will not be represented in the multisample VCF that WhatsHap is going to phase \(the inverse is also likely to be true\). How does WhatsHap handles these cases?

‌

Cheers,

Pedro

**Comment by pdimens** [comment]
I see that this comment is closed, but I'd like a bit more clarification on this topic. Since Whatshap haplotag already has the machinery to use the BX tags to inform phasing of bam files from a phased VCF, would it not be possible to include machinery in whatshap phase to take advantage of BX linked-read information to phase an unphased VCF file using unphased BAMs?

**Comment by marcelm** [comment]
See #238 for the most recent attempt to make this work.

`haplotag` doesn’t do any phasing; it only transfers the phasing information from a VCF to the reads in a BAM file. Its main task is to determine which alleles each read contains and to then estimate which of the haplotypes it fits better. This is relatively simple because the haplotype is given. Handling the BX tag is also simple because the only additional complication it adds is that all reads with the same BX tag (within a certain distance) are to be treated as having the same haplotype.

To support BX tags even for phasing (`whatshap phase`), what I tried in #238 was similar: To treat all reads with the same BX tag as essentially being the same read (possibly with "holes" in it). We already do this for paired-end reads: These are treated as a single read with a hole in the middle. So read clouds could be treated as "multi-end" reads. One (perhaps the main) problem is how to merge the individual reads into a single read where they overlap.

I don’t quite remember why I abandoned #238. Maybe it even works? It definitely needs testing. If you want, I could give you instructions on how to install that development branch.

**Comment by tobiasmarschall** [comment]
The default phasing algorithm is not very well suited for the sparse nature of linked reads. So while the approach described by @marcelm works in principle, it will not be able to use all data at once and will downsample quite aggressively during the read selection phase. Given that the LongRanger platform provides a good phasing engine optimized for linked reads and that 10x discontinued the genomics kit, we concluded that improving linked read phasing is  not a priority for Whatshap development. (That being said, it could be done. Potentially even the polyploid phasing algorithm might be suitable for this, CC @schrins).

**Comment by pdimens** [comment]
Thanks for this valuable discussion. The reason I ask is because while 10x discontinued their linked reads, new (and cheap) non-commercial methods have and continue to emerge like stFLR, TELLseq,  and haplotagging. Longranger too has been abandoned by 10X, so I don't see it being a reliable long term solution.

**Comment by tobiasmarschall** [comment]
@pdimens ok, good point. Could you point us to public data sets from these protocols?
