### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by marcelm** [whatshap/whatshap#232]
**[Original report](https://bitbucket.org/whatshap/whatshap/issue/232) by Zoe Luo (Bitbucket: [Zoe Luo](https://bitbucket.org/Zoe Luo), ).**

----------------------------------------

Hi WhatsHap team,

I am trying to phase variants for a single individual using the following command

`${dir}/whatshap-env/bin/whatshap phase -o ${out} --reference=${fastaReference} ${inVCF} ${inCRAM}`

where  $\{inVCF\} is a vcf.gz file. And I got the following error message:  
`This is WhatsHap 0.19.dev203+g07b6a0d running under Python 3.8.2`  
`Traceback (most recent call last):`  
`File "/nesi/nobackup/uoa02888/kakapo/whatshap-env/bin/whatshap", line 8, in <module>`  
`sys.exit(main())`  
`File "/scale_wlg_nobackup/filesets/nobackup/uoa02888/kakapo/whatshap-env/lib/python3.8/site-packages/whatshap/main.py", line 83, in main`  
`module.main(args)`  
`File "/scale_wlg_nobackup/filesets/nobackup/uoa02888/kakapo/whatshap-env/lib/python3.8/site-packages/whatshap/cli/phase.py", line 1104, in main`  
`run_whatshap(**vars(args))`  
`File "/scale_wlg_nobackup/filesets/nobackup/uoa02888/kakapo/whatshap-env/lib/python3.8/site-packages/whatshap/cli/phase.py", line 346, in run_whatshap`  
`PhasedVcfWriter(`  
`File "/scale_wlg_nobackup/filesets/nobackup/uoa02888/kakapo/whatshap-env/lib/python3.8/site-packages/whatshap/vcf.py", line 818, in init`  
`super().init(in_path, command_line, out_file)`  
`File "/scale_wlg_nobackup/filesets/nobackup/uoa02888/kakapo/whatshap-env/lib/python3.8/site-packages/whatshap/vcf.py", line 750, in init`  
`contigs, formats, infos = missing_headers(in_path)`  
`File "/scale_wlg_nobackup/filesets/nobackup/uoa02888/kakapo/whatshap-env/lib/python3.8/site-packages/whatshap/vcf.py", line 665, in missing_headers`  
`with VariantFile(path) as variant_file:`  
`File "pysam/libcbcf.pyx", line 4036, in pysam.libcbcf.VariantFile.init`  
`File "pysam/libcbcf.pyx", line 4299, in pysam.libcbcf.VariantFile.open`  
`File "pysam/libchtslib.pyx", line 518, in pysam.libchtslib.HTSFile.tell`  
`NotImplementedError: seek not implemented in files compressed by method 1`

Any help would be greatly appreciated!

Many thanks,

Zoe

**Comment by sachingadakh** [comment]
> **Original comment by Zoe Luo (Bitbucket: [Zoe Luo](https://bitbucket.org/Zoe Luo), ).**
> 
> Hi Tobias Thanks for your reply! Yes, the problem has been solved. The input .gz file needs to be compressed by bgzip not gzip. Cheers,Zoe

Thank you for this answer. I think the author of the tool should mention this in their tutorial.
