### ISSUE TITLE
Haplotype Block Size

### ISSUE THREAD

**Issue by vahidAK** [whatshap/whatshap#240]
Hi,
The gtf file produced by _whatshap stats_ represnets haplotypes block sizes, right?
For example at this haplotype block:
chr10_GL383545v1_alt    Phasing exon    26768   92760   .       +       .       gene_id "26768"; transcript_id "26768.1";

the haplotype block size is 92,760  -  26,768= 65,992  ?

Is it correct?
If yes, there are many 1bp or zero bp block sizes in my stat output. I was wondering is it common to have a haplotype block size of 1?  How that can be possible?

Thanks,
Vahid.

**Comment by tobiasmarschall** [comment]
Dear Vahid,

I don't remember from the top of my head how `stats` represents unphased variants in a GTF. Could you check whether these short block lengths in the GTF correspond to unphased variants in the VCF? (And potentially paste a few lines from both files?)

Best,
Tobias

**Comment by vahidAK** [comment]
Hi @tobiasmarschall ,
Here are the first 20 lines:
![image](https://user-images.githubusercontent.com/46334063/90080548-c1697680-dcbf-11ea-8c44-deee68554fb7.png)

If you could also give me you email I can share files via google drive if it is necessary.
BTW, How can I calculate haplotype block sizes?

**Comment by vahidAK** [comment]
Hi @tobiasmarschall 
Any updates?

**Comment by tobiasmarschall** [comment]
If you could additionally post some corresponding lines from your phased VCF, we can take a look (from the same coordinate range, e.g. 1-20000 if that's not too much to post).

**Comment by pontushojer** [comment]
The GTF entries does *NOT* represent the block sizes (length). The GTF accounts for interleaved blocks which means that entries can contain subsections of a block, including those of size 1. Interleaved phase blocks are visualised as *exons in a gene* in the GTF format. So phased subregions (in bold) of the block is connected by thin lines, see example below with two interleaved blocks:

**GTF**
```
chr22	Phasing	exon	11128706	11131337	.	+	.	gene_id "11128706"; transcript_id "11128706.1";
chr22	Phasing	exon	11133782	11137914	.	+	.	gene_id "11133782"; transcript_id "11133782.1";
chr22	Phasing	exon	11150424	11152723	.	+	.	gene_id "11128706"; transcript_id "11128706.1";
chr22	Phasing	exon	11160121	11160241	.	+	.	gene_id "11133782"; transcript_id "11133782.1";
```

**IGV**
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/27061883/201371208-dae3f4ab-8bda-4232-b741-e3aa219dcd4f.png">

**Comment by vahidAK** [comment]
Hi @pontushojer ,

Thanks for the info. 

Yeah, I figured that out back then. Sorry for not updating the issue.

Thanks,
Vahid

**Comment by pontushojer** [comment]
> Yeah, I figured that out back then. Sorry for not updating the issue.

No worries @vahidAK! I thought that might be the case but figured that it would be useful to post an answer for anyone who came upon this issue in the future.
