### ISSUE TITLE
Minor issues in polyphase code

### ISSUE THREAD

**Issue by schrins** [whatshap/whatshap#241]
There are two small things in the current polyphase code, which need to be fixed at some point.
1. In a recent publication, we mentioned that the our model falls back to a heuristic during the threading stage when phasing more than 6 haplotypes. This is due to the running time scaling exponentially with the ploidy. However, the heuristic is actually disabled right now, which went unnoticed, because we only tested up to a ploidy of 6 in our paper.
2. I discovered a bug in the cluster editing solver, which could cause faulty clusterings in very rare constellations. These constellations did not occur in our tested instances, but I have a small and dense graph (as direct input into the solver), which causes a lot of error messages. The fix is minimal, but it changes the results on the paper's instances minimally.

**Comment by tobiasmarschall** [comment]
Hi Sven, what's the timeline for this? Tobias

**Comment by schrins** [comment]
I can more or less fix this right away. I will push the changes to a new branch tomorrow.
