### ISSUE TITLE
Add option --no-ped-warning

### ISSUE THREAD

**Issue by tobiasmarschall** [whatshap/whatshap#245]
When working with large ped files, e.g. many trios, it's easy to get flooded with warnings like this:
```
WARNING: Relationship NA20279/NA20282/NA20278 ignored because at least one of the individuals was not given by --samples.
WARNING: Relationship NA20281/None/None ignored because at least one of the individuals is unknown
```
Would be nice to have an option `--no-ped-warning` to turn those off.

**Comment by marcelm** [comment]
Are these warnings even necessary? Just changing from 'logger.warning' to 'logger.debug' would get rid of them and one could still see them with `--debug`. We could also suppress all but the first of these warnings (and adjust the message accordingly).

**Comment by tobiasmarschall** [comment]
I like the idea of suppressing all but the first one (while giving the hint that all warnings can be displayed by adding `--debug`). While we are at it we could do the same for the `Skipping duplicated position` warnings...
