### ISSUE TITLE
Remove `phase --full-genotyping`

### ISSUE THREAD

**Issue by GuillaumeHolley** [whatshap/whatshap#248]
Hi there,

I am running WhatsHap 1.0 using the following command:
``` whatshap phase --full-genotyping --include-homozygous --distrust-genotypes --mapq 1 --chromosome ${CHR} -r ${REF} -o ${OUT_VCF} ${IN_JOIN_VCF} ${IN_BAMS}```

The command runs nicely for some of the chromosomes and we're getting nice results out of it. But the command fails towards the end for some other chromsomes:

```
======== Writing VCF
Done writing VCF
Traceback (most recent call last):
  File "<REDACTED>/whatshap", line 11, in <module>
    sys.exit(main())
  File "<REDACTED>/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "<REDACTED>/whatshap/cli/phase.py", line 1104, in main
    run_whatshap(**vars(args))
  File "<REDACTED>/whatshap/cli/phase.py", line 643, in run_whatshap
    assert distrust_genotypes
AssertionError
```

The issue seems related to what happened in #127 but there is not much information to work with in this issue :)

Any help would be appreciated :) Thanks!
Guillaume

**Comment by tobiasmarschall** [comment]
Hi Guillaume,

I don't have time to look at this in detail right now, but maybe there's a quick workaround. Actually, think `--full-genotyping` should be removed or at least marked as deprecated, because `whatshap genotype` is much better tested (see http://dx.doi.org/10.1186/s13059-019-1709-0) . So you could try running `whatshap genotype` first, and then `whatshap phase` on the resulting VCF. Then, there shouldn't be a need to use the `--distrust-genotypes` option because the genotypes have been computed in a haplotype aware manner and should be compatible with the input set of reads. If you have a way to assess the quality of the results, I'd be curious to hear your verdict... :)

Best,
Tobias

**Comment by GuillaumeHolley** [comment]
Hi Tobias,

Thanks for your quick answer :) Using `whatshap genotype` first and then `whatshap phase` afterwards is working like a charm for all the chromosomes.  I will of course let you know about the quality of the results as soon as I can do a proper benchmarking. 
However, it seems that a lot of information from the information fields are not present in the output of `whatshap genotype`. The field `PL` is never filled in (although it can be computed from `GL` which is present as I understand it), neither are the fields `DP` and `AD`. Any particular reason for that?

**Comment by tobiasmarschall** [comment]
Great to hear it worked. Your questions are for @eblerjana to answer...

**Comment by eblerjana** [comment]
Hi Guillaume,

sorry for the late reply. You are right, adding the PL field should indeed be simple. WhatsHap derives genotypes by considering possible bipartitions of the reads into the two haplotypes. In this way, information of neighboring variants helps to derive a genotype for a variant position. Therefore, it can happen that the genotype predicted at a position does not reflect the one that would be expected based on the amount of REF and ALT alleles seen in the reads at a single position only. This is why we are currently not reporting it. However, adding that information would probably be not difficult. The DP field can be added as well (but note that WhatsHap uses a heuristic to subsample reads to max. 30x coverage at each variant position, so DP would report the depth after this sampling step).

Best,
Jana

**Comment by GuillaumeHolley** [comment]
Hi @eblerjana,

I just realized that I have never answered back, my apologies. Thank you for all these details. I would be happy if you could add the PL field in a subsequent version of WhatsHap if it is not too much trouble. Bcftools can compute the PL field from the GL field but I think it is more convenient for pipelines to eliminate as many steps as possible. I also think adding the DP field would make sense too even with the subsampling.

**Comment by tobiasmarschall** [comment]
Re-opening as a reminder to retire the old code in `phase --full-genotyping`

**Comment by tobiasmarschall** [comment]
Also, we should pick up Guillaume's suggestions about PL and DP.

**Comment by marcelm** [comment]
See also #127

**Comment by marcelm** [comment]
> Also, we should pick up Guillaume's suggestions about PL and DP.

moved to #291
