### ISSUE TITLE
Haplotagging error in 1.0 that doesn't occur in 0.18

### ISSUE THREAD

**Issue by williamrowell** [whatshap/whatshap#249]
ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/10XGenomics_ChromiumGenome_LongRanger2.2_Supernova2.0.1_04122018/GRCh38/NA24385_300G/NA24385.GRCh38.phased_variants.vcf.gz

```bash
whatshap haplotag --output "${OUTBAM}" \
        --reference "${REF}" \
        --ignore-read-groups \
        "${VCF}" \
        "${INBAM}"
```

I'm using the VCF above to haplotag a PacBio HiFi BAM.  The command above works for whatshap/0.18, but the same command fails for whatshap/1.0 with the message below:

```bash
Traceback (most recent call last):
  File "/mnt/software/w/whatshap/1.0/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/mnt/software/w/whatshap/1.0/lib/python3.7/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/mnt/software/w/whatshap/1.0/lib/python3.7/site-packages/whatshap/cli/haplotag.py", line 594, in main
    run_haplotag(**vars(args))
  File "/mnt/software/w/whatshap/1.0/lib/python3.7/site-packages/whatshap/cli/haplotag.py", line 536, in run_haplotag
    linked_read_distance_cutoff,
  File "/mnt/software/w/whatshap/1.0/lib/python3.7/site-packages/whatshap/cli/haplotag.py", line 173, in prepare_haplotag_information
    variantpos_to_phaseinfo, variants = get_variant_information(variant_table, sample)
  File "/mnt/software/w/whatshap/1.0/lib/python3.7/site-packages/whatshap/cli/haplotag.py", line 89, in get_variant_information
    phase_info = int(phases[idx].block_id), phases[idx].phase[0]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Were there changes in how the VCF is parsed?

**Comment by marcelm** [comment]
> Were there changes in how the VCF is parsed?

Yes, we switched to using htslib (via pysam) for VCF parsing, which is significantly faster (especially with VCFs that contain many samples), and that way we also support reading `.bcf` files now. However, htslib is quite strict in what types of VCF it accepts. Can you try to run `bcftools view ... > /dev/null` on your file? If you get an error, you know that the file doesn’t quite follow the spec. I’ll have a look myself, it is possible that this is not actually a problem with the VCF.

**Comment by williamrowell** [comment]
There were no errors when I ran `bcftools view NA24385.GRCh38.phased_variants.vcf.gz > /dev/null`.

I think I know what's going on.  This VCF is sorted poorly.  `chr1` is followed by `chr10`, etc.  Sound like a possible cause?

**Comment by marcelm** [comment]
As long as tabix does not complain, the sorting should not be a problem.

I was now able to reproduce the problem on the VCF that you linked. The error occurs at variants that have a `PS` tag whose value is set to `.`. WhatsHap tries to convert this to an integer phase set id, but fails and throws the error message you posted.

**Comment by marcelm** [comment]
I fixed the problem now, can you test the version from master?

**Comment by williamrowell** [comment]
The version from master branch works.  Thank you @marcelm.

**Comment by marcelm** [comment]
Great, thanks for the feedback.
