### ISSUE TITLE
Question: how to interpret the regions in --block-list output

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [whatshap/whatshap#250]
The output from `whatshap stats --block-list` has the columns `from` and `to`, and I was wondering if these positions are inclusive or exclusive, and whether they are 0 or 1 based. I've tried searching for this information in the documentation, but I could not find anything.

**Comment by marcelm** [comment]
Sorry for not getting back earlier. I have now added a section to the documentation to clarify the output format of `--black-list`, see <https://whatshap.readthedocs.io/en/latest/guide.html#whatshap-stats>. Let us know if you have more questions.
