### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by husamia** [whatshap/whatshap#252]
Is there a docker container for WhatHap that keeps up the latest releases

**Comment by tobiasmarschall** [comment]
I'm not aware of a docker container for WhatsHap, it is easy to deploy using [bioconda](https://bioconda.github.io/) though. In which context would a Docker container be useful for you? I'm asking to understand whether we should offer Docker in the future.

**Comment by husamia** [comment]
With a docker container we can deploy the software on cloud services. Also it make it easier for users to run it that don't have experience with installation.

**Comment by marcelm** [comment]
Bioconda automatically builds Docker (and Singularity) images for all packages, so there’s one for WhatsHap as well, see https://biocontainers.pro/#/tools/whatshap .

**Comment by husamia** [comment]
Perfect. Thank you
