### ISSUE TITLE
Outdated user guide for haplotag function

### ISSUE THREAD

**Issue by kisudsoe** [whatshap/whatshap#255]
Hello,

Here I inform you the outdated description of `haplotag` function.

```
whatshap haplotag -o haplotagged.bam --reference reference.fasta phased.vcf alignments.bam
```

The `phased.vcf` has to be changed to `phased.vcf.gz`.

Thanks,
kisudsoe

**Comment by marcelm** [comment]
Thanks for reporting! We should be able to change the `haplotag` command to accept an uncompressed VCF without an index (since `whatshap phase` also accepts one), but for now, I have updated the documentation to make it clear what the requirements are.
