### ISSUE TITLE
Question: column explanation for tsv output whatshap stats

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [whatshap/whatshap#259]
I'm adding support for WhatsHap to MultiQC, but I am confused about how to interpret some of the columns in the stats tsv output. For example, I was expecting the value in the `variants` column to be equal to `phased + unphased`, but this is not the case.

Would it be possible to add a short description of each column in the tsv file to the documentation? I want to be sure that I do not add any wrong guesses about the meaning of each column to the MultiQC report.

**Comment by marcelm** [comment]
Thanks for working on this! I have thought for a while that a MultiQC plugin would be nice, but haven’t had the time to work on it myself. I’ve gone through the source code of `whatshap stats` and have now added a description of the columns to the documentation. I didn’t have time to double-check this by running `whatshap stats` on a file, so if you see something weird, please let me know and I’ll fix it.

**Comment by marcelm** [comment]
https://whatshap.readthedocs.io/en/latest/guide.html#the-tsv-statistics-format
