### ISSUE TITLE
Polyploid version of whatshap haplotag

### ISSUE THREAD

**Issue by rvicedomini** [whatshap/whatshap#267]
Hello,
this question might be also related to #214. Is there any plan to introduce the polyploid version of haplotag (and split) in the main development branch of whatshap?

Thanks,
Riccardo

**Comment by tobiasmarschall** [comment]
Hi Riccardo,

absolutely! Thanks for reminding us. Presently everybody is pretty busy with other tasks, so I expect that might not happen immediately, but please do ping us again if it hasn't happened in (say) a months time.

Best,
Tobias

**Comment by tobiasmarschall** [comment]
PS: I assume you did see the [branch polyploid-haplotag](https://github.com/whatshap/whatshap/tree/polyploid-haplotag), didn't you?

**Comment by rvicedomini** [comment]
Thank you very much for the answer!
Yes I'm already considering the polyploid-haplotag branch. I was just thinking it would be great to have polyploid haplotag in the main branch in order to benefit from all recent whatshap improvements (without having multiple versions installed).

Best,
Riccardo

**Comment by baozg** [comment]
Hi, @tobiasmarschall 

Would the `polyploid-haplotag` will merge into the main branch?

Best,
Zhigui

**Comment by tobiasmarschall** [comment]
That's certainly the plan, but I'm not sure what the status is. @eblerjana or @ptrebert, could you comment?

**Comment by schrins** [comment]
Haplotag should now support polyploid input with #410 being merged. The split command is still diploid, as far as I know. Since there is another issue (#408 ) with the same request, I will close this one and refer to the other for further comments.

**Comment by baozg** [comment]
Great! Thanks for your support!
