### ISSUE TITLE
using polyphase for near diploid genomes

### ISSUE THREAD

**Issue by rrazaghi** [whatshap/whatshap#271]
Hi,

Thank you for implementing whatshap polyphase, this is a very useful tool for the community! I have a few samples that are nearly diploid but karyotyping suggests overrepresentation in a few chromosomes. I know that based on the documentation polyphase does not take copy number variation into account, but was wondering if there's a best practice to phase regions expected to have polyploidy.

Thanks!
Roham

**Comment by tobiasmarschall** [comment]
Dear Roham,

great to hear that WhatsHap is useful to you. You mention an important problem and we hope to address it in a principled way in the future. For now, there might be some workarounds. The first question is whether or not you expect there to be more than two _distinct_ haplotypes for any of the chromosomes. That is, are they expected to be diverged significantly in terms of SNVs/indels, or will there "just" be an extra copy of the existing haplotypes. In the latter case, you might just run diploid phasing and then determine which haplotype was amplified, e.g. by running `whatshap haplotag`, splitting the BAM files by `HP` tag, and then running a copy number caller on the haplotype-specific BAM files. (In the former case, you might need to call copy numbers first and run whatshap polyphase specifically on the regions with ploidy>2). Hope that helps.

Tobias

**Comment by rrazaghi** [comment]
Tobias this is really helpful! I will run some analysis and keep you posted! 

I'll close this issue for now!

Best,
Roham
