### ISSUE TITLE
Difficulty phasing de novos with short paired-end reads

### ISSUE THREAD

**Issue by jbelyeu** [whatshap/whatshap#274]
This may be more of a question than an issue, but I'm testing this tool on a large set of de novo variants using Illumina reads, and none of the single-sample de novos phased. The cohort of samples has 3 generations, so many of the de novos from the second gen are also in the third gen, and many of these phased, but not the ones from the 3rd gen that occur in just one sample. Should I expect whatshap to phase those or is that a more complex case?

Side note: I had to split my whole-cohort VCF into separate per-trio VCFs because of crashing (mostly ram issues). Might be a tough nut to crack but it'd be nice to handle larger inputs.

**Comment by jbelyeu** [comment]
Related question: I phased a bunch of de novos with the whatshap pedigree command for a set of variants whose parent of origin is known from other analyses. The parent of origin results show a very high phase rate (~3/4) but only match the known truth in around half of the phased cases. Any thoughts on what's going on?

**Comment by tobiasmarschall** [comment]
Handling de novo variants properly has been on our todo list for a long time, it's a shame we did not get to it yet. Did you see the discussion in [Issue 82](https://github.com/whatshap/whatshap/issues/82)?

**Comment by jbelyeu** [comment]
I had missed that - thanks! Very helpful
