### ISSUE TITLE
Explained thin line in gtf block 

### ISSUE THREAD

**Issue by dridk** [whatshap/whatshap#277]
Hi,

I just ran your "awesome" application on [TLA dataset](https://www.cergentis.com/files/files/application_notes/cergentis_application_note_human_gdna_tla_protocol.pdf). Briefly, It is a paired-end sequencing with large insert size. 

After creating the phased-block with _whatshap stat --gtf_  I get the following results in IGV.
I wonder what the meaning of the thin line ? 
![image](https://user-images.githubusercontent.com/1911063/101932166-af023980-3bda-11eb-9bee-0214d2bda03a.png)

**Comment by marcelm** [comment]
In a normal GTF file, the thick lines would be exons and the thin lines connecting them introns. We use that file format in `whatshap stats` to show phase sets.

The variants on the thick segments are phased and belong to the same phase set. The section in the middle does not belong to that phase set, and is either unphased or belongs to a different phase set.

I guess that there was at least one read pair that links these two thick regions in your case.

**Comment by marcelm** [comment]
I hope that helped.
