### ISSUE TITLE
Whatshap Haplotagging

### ISSUE THREAD

**Issue by SamCT** [whatshap/whatshap#284]
Hello,

I have been having a lot of trouble getting the read coloring to work successfully in IGV. I've created two different haplotag files, using a phased vcf from whatshap phase --> whatshap haplotag , both have failed. At first I thought it was a discrepancy between my @RG , since I have two samples, each with a set of Illumina and PB reads. The second file I generated was an attempt to correct this discrepancy, but it had no impact. I have haplotag blocks, but it just won't color the reads. Wondering if there is any insights into this problem?

Thank you and thanks for the great tool.
Sam

**Comment by tobiasmarschall** [comment]
From your description I don't understand whether it is the haplotagging or the coloring that doesn't work. Did you have a look at the BAM files to see whether there are reads that did get tagged? That is, reads with and `HP` tag. Could you post the log output of `whatshap haplotag`?

**Comment by SamCT** [comment]
Found 2 samples in input VCF
Keeping 2 samples for haplo-tagging
Found 2 samples in BAM file

== SUMMARY ==
Total alignments processed:                 519087913
Alignments that could be tagged:                    0
Alignments spanning multiple phase sets:            0
haplotag - total processing time: 6542.65646314621
 Full Command:                      whatshap haplotag -o PHASED_Illumina_AND_PB_Corav_version4_bwamem.Jeff_v3.0_haplotag.vcf --reference ref_3.0.fasta PHASED_Illumina_AND_PB_version4_bwamem.Jeff_v3.0.vcf all_bam_nbwamem_pbv4.bam
        Memory (kb):                       4450404
        # SWAP  (freq):                    0
        # Waits (freq):                    6228848
        CPU (percent):                     98%
        Time (seconds):                    6544.82
        Time (hh:mm:ss.ms):                1:49:04
        System CPU Time (seconds):         93.51
        User   CPU Time (seconds):         6340.91



I think you are correct that it failed to tag them, I thought there were HP tags when I used samtools view -bS output.bam | grep 'HP' | less -S and now I am not seeing those tags... My mistake. However, i'm still wondering why the tagging completely failed to initiate...

Sam

**Comment by SamCT** [comment]
So my phased .VCF out of whatshap phase was successful. I am able to see all four bam files within the haplotagged bam (two samples (tSM) and the four respective tID's to each read set. My whatshap phase stats .txt file looks good, still wondering why this haplotagging was unsuccessful. All I can think of is that it is the result of a failed, concatenated bam file (which were the all four of the separate bam files, concatenated, and used to produce the original phased .VCF). When I produced the original phased .VCF l did not use a concatenated bam and instead provided each bam file in the whatshap phase command. Perhaps that's what I need to do in the haplotag function ?

**Comment by ptrebert** [comment]
any chance you could reduce your input data to a small test dataset (below a few gigs)?

**Comment by SamCT** [comment]
I managed to reduce the input dataset to a vcf and bam file that covers 1-50000 bp. Reminder that I have two samples, each with two read groups (illumina and pacbio). I did get an output bam file from whatshap haplotag, but the colored reads are odd -- I have two different colors for the same sample and same readgroup, but no colors for the other sample or other respective readgroups. 

![test_RG_WHATSHAP_HAPLOTAG](https://user-images.githubusercontent.com/35304435/115923872-ca583d80-a433-11eb-82bd-89e4f758f77d.PNG)

**Comment by marcelm** [comment]
Can you share that dataset with us?

**Comment by SamCT** [comment]
The filetype is not supported here. May I email you my test files?

Thanks
Sam

**Comment by SamCT** [comment]
[Whatshap_HAPLOTAG_TestFiles_50kb.zip](https://github.com/whatshap/whatshap/files/6385827/Whatshap_HAPLOTAG_TestFiles_50kb.zip)

Here is my data set of a short segment (50kb)

Sam

**Comment by marcelm** [comment]
Thanks. I hope a bit that @ptrebert has some time to take a look as I will soon be absent for two weeks.

**Comment by ptrebert** [comment]
Sure thing!

**Comment by ptrebert** [comment]
With v1.1, I get haplotagged reads for the scaffold `scaffold_1_length_72278661` (total of ~8.7k), and then WH aborts because there is no sequence in the reference fasta for the scaffold `'scaffold_2_length_71305833'` (which is irrelevant as there are no variants on that scaffold in the test data set).
Reading this whole issue again, I don't see which version of WH was used when this error occurred?

**Comment by SamCT** [comment]
This occurred on v1.0. Yes I did scrape my vcf and bam file from a larger one in order to reduce the size of this example data set, so that makes sense there was an abort. I think what is odd is that only one read group is getting color coded of the four...

**Comment by ptrebert** [comment]
When I do a `samtools split` on the test data set and count the reads per readgroup BAM output, I get the following:

```python
Jeff_50kb_haplotagTest_2_noPG_1_0.bam
Counter({'OSU_252.146_RG_A': 13278})
Jeff_50kb_haplotagTest_2_noPG_1_1.bam
Counter({'OSU_414.062_RG_A': 18194})
Jeff_50kb_haplotagTest_2_noPG_1_2.bam
Counter()
Jeff_50kb_haplotagTest_2_noPG_1_3.bam
Counter({'OSU_414.062_RG_B': 1})
ungrouped.bam
Counter()
```
There are essentially only two read groups in the file (ignoring the one read alignment for OSU_414.062_RG_B). When I look at the haplotagged BAM in IGV, I see two colors (coloring by read group or by sample), and, e.g. multiple colors when coloring by phase set (PS tag) - all as expected given the input the way I see it.

**Comment by ptrebert** [comment]
Closing this now, does not seem to be a WhatsHap bug.
