### ISSUE TITLE
Can I use Medaka to determine gene copy number?

### ISSUE THREAD

**Issue by mlosilla** [whatshap/whatshap#285]
Hi,

Thank you for providing and supporting Medaka.

I am studying one gene duplication and I was wondering if I could use medaka to determine how many copies of the gene are present in each of my samples. This gene is ~2000bp, and I amplicon-sequenced it with ONT, so all reads completely span the gene. My samples were barcoded so there are reads from only one individual in each analysis.

Although all the species I am looking into have diploid genomes, my target gene may be present in one, two, three (more?) copies in each species. Hence, for the purposes of this gene, they could be considered as of unknown ploidy.

My goals are 1) to figure out how many copies of my target gene are there in each sample, and 2) to get a consensus sequence for each copy.

Do you think medaka could be applicable here? Potentially useful options I have thought about are:

- medaka smolecule to generate a consensus sequence
- medaka_haploid_variant: Is there a limit on how many haplotypes it can find? 
- medaka_variant: If this can use whatshap polyphase, I could do several runs with different ploidy values (I plan to explore using whatshap directly as well) 

Any thoughts or suggestions are appreciated

Thank you
Mau

**Comment by tobiasmarschall** [comment]
Wrong issue tracker?

**Comment by tobiasmarschall** [comment]
(Let me know if I'm missing something, happy to reopen this in that case...)

**Comment by mlosilla** [comment]
Hi Tobias,

yes, wrong issue tracker, how embarrassing. I am exploring several ways to analyze this, but I have already started a thread on the whatshap repo and I will reply there when I make progress.

My apologies, please delete this thread if possible

Thanks
