### ISSUE TITLE
Haplotag not tagging any reads

### ISSUE THREAD

**Issue by skambha6** [whatshap/whatshap#297]
Hi,

I'm trying to run whatshap haplotag to assign reads to haplotype-separated bam files, using the following command. My sample is a cross between two parental mice that are completely homozygous and have fully known reference genomes.

`whatshap haplotag -o 210205_mouse_6.cc037.haplotagged.bam --ignore-read-groups --output-haplotag-list 210205_mouse_6.cc019_cc037.haplotag_output_list.tsv --reference cc037_mm37.fa cc019_cc037.only_snps.fixed.phased.vcf 210205_mouse_6.cc037.sorted.bam`

However I run into the following output message, with no tagged alignments:

```
Found 1 samples in input VCF
Keeping 1 samples for haplo-tagging
Found 0 samples in BAM file

== SUMMARY ==
Total alignments processed:                  35079256
Alignments that could be tagged:                    0
Alignments spanning multiple phase sets:            0
haplotag - total processing time: 21144.320340156555
```

Below is the beginning of my VCF file. The VCF file was generated manually by using the output of MUMMER to report SNPs between the two fully known parental genomes. I manually added the GT:PS tag - since the parents are completely homozygous, every identified SNP should be part of the same haplotype. 
```
##fileformat=VCFv4.2
##fileDate=20210308
##source=my-mummer-2-vcf.py
##reference=/ibox/afeinbe2/skambha6/cc_ont/cc_genom/cc037_mm37.fa
##contig=<ID=chr1,length=197155490>
##contig=<ID=chr2,length=181700934>
##contig=<ID=chr3,length=159566866>
##contig=<ID=chr4,length=155588084>
##contig=<ID=chr5,length=152495207>
##contig=<ID=chr6,length=149483427>
##contig=<ID=chr7,length=152511887>
##contig=<ID=chr8,length=131706219>
##contig=<ID=chr9,length=124042673>
##contig=<ID=chr10,length=129985824>
##contig=<ID=chr11,length=121826504>
##contig=<ID=chr12,length=121230488>
##contig=<ID=chr13,length=120254203>
##contig=<ID=chr14,length=125169760>
##contig=<ID=chr15,length=103474057>
##contig=<ID=chr16,length=98306338>
##contig=<ID=chr17,length=95262915>
##contig=<ID=chr18,length=90765997>
##contig=<ID=chr19,length=61324751>
##contig=<ID=chrX,length=166626966>
##contig=<ID=chrM,length=16299>
##INFO=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1
chr1    3000444 .       T       A       .       .       .       GT:PS   0|1:1000
chr1    3000608 .       T       G       .       .       .       GT:PS   0|1:1000
chr1    3000817 .       G       A       .       .       .       GT:PS   0|1:1000
chr1    3002454 .       T       C       .       .       .       GT:PS   0|1:1000
chr1    3002922 .       G       A       .       .       .       GT:PS   0|1:1000
chr1    3017344 .       G       T       .       .       .       GT:PS   0|1:1000
chr1    3017715 .       C       G       .       .       .       GT:PS   0|1:1000
chr1    3017734 .       C       T       .       .       .       GT:PS   0|1:1000
chr1    3017735 .       C       G       .       .       .       GT:PS   0|1:1000
chr1    3017820 .       G       A       .       .       .       GT:PS   0|1:1000
chr1    3017880 .       T       C       .       .       .       GT:PS   0|1:1000
chr1    3017893 .       G       A       .       .       .       GT:PS   0|1:1000
chr1    3017921 .       C       T       .       .       .       GT:PS   0|1:1000
chr1    3018041 .       G       A       .       .       .       GT:PS   0|1:1000
chr1    3018489 .       C       T       .       .       .       GT:PS   0|1:1000
chr1    3018823 .       T       G       .       .       .       GT:PS   0|1:1000
chr1    3019049 .       A       G       .       .       .       GT:PS   0|1:1000
chr1    3019793 .       G       T       .       .       .       GT:PS   0|1:1000
chr1    3019814 .       T       G       .       .       .       GT:PS   0|1:1000
```

Any advice on what might be going wrong here, or if there is a problem with my VCF file, would be greatly appreciated.

Thank you!
Sandeep

**Comment by tobiasmarschall** [comment]
Dear Sandeep,

the message `Found 0 samples in BAM file` makes me wonder whether your BAM file has sample information as a part of the read group(s). Could you check the header of your BAM for `@RG` lines? If not, `samtools addreplacerg` might help to add them...

Tobias

**Comment by skambha6** [comment]
Hi Tobias,

My understanding was that the `--ignore-read-groups` tag tells whatshap to assume all the reads come from the same sample, but I can try using `samtools addreplacerg` and see if that works. 

Thank you!
Sandeep

**Comment by tobiasmarschall** [comment]
Sorry, I overlooked the `--ignore-read-groups`. Still interesting to try to give us hints what might be going wrong.

**Comment by skambha6** [comment]
Hi Tobias,

After using samtools addreplacerg to add the @RG tag (but not the SM field) and running with --ignore-read-groups, I get the following output:

```
Found 1 samples in input VCF
Keeping 1 samples for haplo-tagging
Found 1 samples in BAM file
WARNING: Read group "sample1" does not contain an SM field to assign it to a sample. Use --ignore-read-groups to use these alignments anyway.

== SUMMARY ==
Total alignments processed:                  35079256
Alignments that could be tagged:                    0
Alignments spanning multiple phase sets:            0
haplotag - total processing time: 17135.466502904892
```

Best,
Sandeep

**Comment by skambha6** [comment]
I also tested it specifying the SM field and running on a single chromosome, but that didn't seem to resolve the issue:

```
Found 1 samples in input VCF
Keeping 1 samples for haplo-tagging
Found 1 samples in BAM file

== SUMMARY ==
Total alignments processed:                    833179
Alignments that could be tagged:                    0
Alignments spanning multiple phase sets:            0
haplotag - total processing time: 514.3467786312103
```

If you have any other suggestions that would be greatly appreciated.

Thanks!
Sandeep

**Comment by ptrebert** [comment]
any chance you could reduce your input data to a small test dataset (below a few gigs)?

**Comment by cassytha** [comment]
This issue helps me out. The option --ignore-read-groups is really important for me since many other alignment algorithm beside bwa doesn't require the read group information, which is required by WhatsHap.

**Comment by zhenzhenyang-psu** [comment]
Hello there,
This issue also occurred to me. Whatshap haplotagging subcommand didn't tag any reads of the bam file. The output of my haplotagging is:
Found 1 samples in input VCF
Keeping 1 samples for haplo-tagging
Found 0 samples in BAM file

== SUMMARY ==
Total alignments processed:                   7378236
Alignments that could be tagged:                    0
Alignments spanning multiple phase sets:            0
haplotag - total processing time: 1784.6758961677551
Total number of reads in haplotag list: 7378236
Total number of haplo-tagged reads: 0
Total number of untagged reads: 7378236

My haplotag and split command is as follows:
REF=GCF_009914755.1_T2T-CHM13v2.0_genomic.chr.fa
VCF=CHM13v2.0_HG2-T2TQ100-V1.1.vcf
BAM=corrected.hifi.onto.CHM13.minimap2.out.no2308.sorted.bam

whatshap haplotag --ignore-read-groups   -o haplotagged.bam --output-haplotag-list haplotagged.read.list --reference $REF $VCF $BAM
conda activate hifi_phase
samtools index haplotagged.bam
conda activate /public/home/yangzhzh/miniconda3/envs/deepvariant_whatshap
whatshap split --discard-unknown-reads --output-h1 hap1 --output-h2 hap2 --output-untagged unassigned --read-lengths-histogram output.hist haplotagged.bam haplotagged.read.list

The following is the minimap command to create the bam file. 
REF=GCF_009914755.1_T2T-CHM13v2.0_genomic.chr.fa

FA=/public/home/sunzhg/pipeline/input/HG002/HG002_hifiasm_correctHifiReads/HG002.hifiasm.0.19.9.final.asm.ec.fa

/public/home/sunzhg/tools/minimap2-2.28_x64-linux/minimap2 -ax map-hifi -t "$t" -N 5 --secondary=no $REF $FA > corrected.hifi.onto.CHM13.minimap2.out.sam
source ~/miniconda3/bin/activate 
conda activate hifi_phase 

head=corrected.hifi.onto.CHM13.minimap2.out
samtools  view -@ "$t" -F 2308 -h -Sb $head.sam > $head.no2308.bam
samtools  sort -@ "$t" -o $head.no2308.sorted.bam  $head.no2308.bam
samtools  index $head.no2308.sorted.bam

My vcf also contains heterozygous SNPs. 
chrX	154257476	.	G	A	30	.	LCR=0	GT:AD	0|1:0,1
chrX	154257482	.	G	A	30	.	LCR=0	GT:AD	0|1:0,1
chrX	154257488	.	G	A	30	.	LCR=0	GT:AD	0|1:0,1
chrX	154257494	.	G	A	30	.	LCR=0	GT:AD	0|1:0,1
chrX	154257505	.	T	A	30	.	LCR=0	GT:AD	0|1:1,1
chrX	154257546	.	GT	G	30	.	LCR=0.5	GT:AD	0|1:1,1


i wonder if you could tell me what might be going wrong. 

Thank you very much!
Looking forward to the reply. 
zhenzhen

**Comment by zhenzhenyang-psu** [comment]
please ignore. I just figured out that by using the .gz vcf file 'GRCh38_HG2-T2TQ100-V1.1.vcf.gz', it worked!

**Comment by tobiasmarschall** [comment]
Glad you could solve it.
