### ISSUE TITLE
Non phased SNPs within the phaseblocsk

### ISSUE THREAD

**Issue by sstwins21** [whatshap/whatshap#298]
Hi,

I am trying to phase the diploid sample just using the paired-end illumina short reads.  Coverage of the samples varies, but higher ones go up to 40X.

I notice that within the phase blocks, there are still more un-phased loci than phased ones...
Would this be due to using the short reads only? From my understanding, those un-phased loci are the ones that located between paired-end and that do not connected to the reads that are used for phasing? 

Thus, would this problem be solved if we use nanopore sequence?

Kind regards,
Shane

**Comment by tobiasmarschall** [comment]
Dear Shane,

yes, phasing completeness is mostly a function of read length, because you can only phase a heterozygous variant if there's a read that covers it AND another neighboring heterozygous variant. So yes, long reads would help.

Tobias

**Comment by sstwins21** [comment]
Hi Tobias,

Yes, we might get nanopore data, but if we have more coverage on illumina data would that help too?
If there are more short reads that there might be more overlaps between the short reads?

Kind regards,
Shane

**Comment by tobiasmarschall** [comment]
Higher coverage for Illumina will help only marginally, if at all. If two het variants are further apart than the Illumina insert size, then all the coverage in the world does not connect them...

**Comment by sstwins21** [comment]
Thank you for your help Tobias !
