### ISSUE TITLE
Phasing MNPs and complex variants

### ISSUE THREAD

**Issue by Tierhon** [whatshap/whatshap#300]
Hi,
while phasing, I got this error:
AssertionError: Strange variant: VcfVariant(1303, 'TGGT', 'CTGG')
This is a complex variant as called by FreeBayes. I thought they were supported by reading https://github.com/whatshap/whatshap/issues/3 and https://github.com/whatshap/whatshap/issues/38, specifically https://github.com/whatshap/whatshap/issues/3#issuecomment-653053971.

While looking at the code (https://github.com/whatshap/whatshap/blob/71b04980a4e62d177134f33bc8fc5e4c02ffd47d/whatshap/variants.py#L235 and further), it looks like only SNVs, insertions and deletions are supported. I tried browsing through the commits, but couldn't find where the support was removed.

I get this error by using --indels, without it it just works fine. I wanted to see if I could haplotag more PacBio reads (CLRs) with indels phased.

Thank you.

Ole

**Comment by marcelm** [comment]
You need to provide a reference sequence using `--reference`. If you don’t do this, WhatsHap falls back to an older way of detecting variants in the reads, which does not support MNPs and complex variants.

Which WhatsHap version are you using? More recent ones will force you to use either `--reference` or `--no-reference`, and you should get a warning if you use `--no-reference`.

**Comment by Tierhon** [comment]
Ops, I seem to have made a mistake. I provided --reference to a $REF that I set up earlier in the script, but I wrapped the command in single quotes and that didn't work. By wrapping it in double quotes it seems to work just fine. 

I didn't think it investigate this before you mentioned it. Now I have to go back and look carefully at some earlier results. 

Thank you.

Ole

**Comment by marcelm** [comment]
Great, I’m glad you solved it!
