### ISSUE TITLE
working with gatk output

### ISSUE THREAD

**Issue by marksantcroos** [whatshap/whatshap#309]
Hi,

While I have read your recommendation of using Freebayes in the documentation, there are lots of GATK VCF's in the wild, especially in clinical settings.

As you are probably aware, GATK does local realignment, leading to situations where it finds variants that are not supported by the original BAM files. It has the option to output the "realigned bam file" (`-bamout`), but that one is rather artificial and mainly intended for debugging purposes.

I guess my question is, do you have a set of recommendations to use whatshap in combination with GATK VCF's?

Thanks!

Regards,

Mark

**Comment by tobiasmarschall** [comment]
I'm not aware of any issues with GATK VCFs and they should be usable "out of the box". Since WhatsHap detects alleles from BAM files using a realignment procedure as well, it should be robust to different variant representations.

**Comment by ptrebert** [comment]
I am closing this now due to 4 weeks of silence after the question has been answered.
