### ISSUE TITLE
whatshap haplotag for polyploid phased sample - 0 reads tagged

### ISSUE THREAD

**Issue by markopetek** [whatshap/whatshap#310]
Running the following command with a phased **tetraploid** vcf and bam file with defined sample name in the RG field, the reads in the output bam are not tagged. To generate the bam, I've mapped the corrected nanopore fastq with minimap2 (I've generated the fastq from fast and added fake QV=40 to all bases using `fastaq to_fake_qual`)  : 

```
whatshap haplotag -o ../output/raw_corr_potatov61.haplotagged.bam \
--region chr10:57940308-58013972 \
--output-haplotag-list ../output/haplotaglist_raw_corr_potatov61.tab \
../output/freebayes_raw_corr_potatov61.phased.vcf.gz \
../input/raw_corr_potatov61.addRG.bam
```
> Found 1 sample(s) in input VCF
> Keeping 1 sample(s) for haplo-tagging
> Found 1 sample(s) in BAM file
> Reading alignments for sample 'samplix' and detecting alleles ...
> Found 0 reads covering 0 variants
> 
> == SUMMARY ==
> Total alignments processed:                     31501
> Alignments that could be tagged:                    0
> Alignments spanning multiple phase sets:            0
> haplotag - total processing time: 1.2941832542419434

In the output haplotag list all reads have values for haplotype and phaseset "none".

----
here is also the `whatshap polyploid` command and its stdout run before `haplotag`: 

```
whatshap polyphase \
-t 30 \
-o ../output/freebayes_raw_corr_potatov61.phased.vcf \
--reference ../../_A_02_Samplix_assembl-dry/input/genome/DM_1-3_516_R44_potato_genome_assembly.v6.1.filtered.scaffoldMerged.fasta \
--ploidy 4 \
--mapq 10 \
--verify-genotypes \
--mapping-quality 10 \
--ce-refinements 3 \
../output/freebayes_raw_corr_potatov61.vcf \
../input/raw_corr_potatov61.addRG.bam
```
> This is WhatsHap (polyploid) 1.1 running under Python 3.9.2
> ======== Working on chromosome 'chr10'
> ---- Processing individual samplix
> Number of variants skipped due to missing genotypes: 0
> Number of remaining heterozygous variants: 1611
> Reading alignments for sample 'samplix' and detecting alleles ...
> Found 15385 reads covering 1611 variants
> Verify genotyping of samplix
> 1611 16111611
> [0/0/0/0, 0/0/1/1, 0/0/0/1, 0/0/1/1, 0/0/1/1, 0/0/0/1, 0/0/0/0, 0/0/0/1, 0/0/0/0, 0/0/1/1, 0/1/1/1, 0/0/0/0, 0/0/0/0, 0/0/0/0, 
> --- deleted manually ---
0/0/1/1] 1611
> 1611
> Number of variants removed due to inconsistent genotypes: 1026
> Number of remaining heterozygous variants: 585
> Reading alignments for sample 'samplix' and detecting alleles ...
> Found 14822 reads covering 585 variants
> Kept 13972 reads that cover at least two variants each
> Detecting connected components with weak interconnect ..
> Split heterozygous variants into 2 blocks (and 0 singleton blocks).
> Phasing block 2 of 2 with 395 reads and 35 variants.
> Phasing block 1 of 2 with 13577 reads and 550 variants.
> Finished block 2.
> Finished block 1.
> ======== Writing VCF
> Done writing VCF
> 
> == SUMMARY ==
> Maximum memory usage: 1.266 GB
> Time spent reading BAM/CRAM:                    4.5 s
> Time spent parsing VCF:                         0.1 s
> Time spent verifying genotypes:                 2.5 s
> Time spent detecting blocks:                    0.3 s
> Time spent phasing blocks:                    909.2 s
> Time spent writing VCF:                         0.1 s
> Time spent on rest:                             0.2 s
> Total elapsed time:                           916.8 s
>

**Comment by eblerjana** [comment]
Hi @markopetek,

did you check how many variants could actually be phased in the phasing step? It seems like most of them are filtered out due to inconsistent genotypes (1026 out of 1611, see log). Since haplotag needs phased genotypes, this might explain why it was not able to tag anything. If possible, you can also send my your input VCF and I can have a closer look into that issue. 

Best,
Jana

**Comment by markopetek** [comment]
Here is the phased VCF:
[freebayes_raw_corr_potatov61.phased.vcf.gz](https://github.com/whatshap/whatshap/files/6435142/freebayes_raw_corr_potatov61.phased.vcf.gz)

I also tried running `whatshap polyploid` without the "--verify-genotypes" parameter. Then I don't get and get the genotypes filtered but still haplotag gives the same output.

**Comment by markopetek** [comment]
Is polyploid haplotag already merged into the main branch (I've installed whatshap using conda)?

I'm asking because of the open issue https://github.com/whatshap/whatshap/issues/267

**Comment by eblerjana** [comment]
Sorry for the delay. When you run without `--verify-genotypes`, does the output VCF contain phased genotypes? Looking at the VCF that you shared, it seems like many variants are multi-allelic, and as far as I know, `whatshap` would skip those. Maybe this is another reason why many variants are left untyped. The polyploid haplotag command is not yet merged to master, we are still working on this.

**Comment by markopetek** [comment]
When I run without `--verify-genotypes` the phased VCF has cca 300 more variants with the PS field than when running with this option. I'm attaching that VCF also:
[freebayes_raw_corr_potatov61.phased.vcf.gz](https://github.com/whatshap/whatshap/files/6493438/freebayes_raw_corr_potatov61.phased.vcf.gz)

Still, I don't understand why I don't get any reads tagged by `whatshap haplotag` although I have 500-800 variants called by `whatshap polyploid` in that 50 kb region and coverage of nanopore reads >100x. Any thoughts on that?

**Comment by eblerjana** [comment]
Thanks! I just opened the VCF, but I don't see any phased genotypes (or PS tags) and also the header of the VCF file misses the command line used to create the phased VCF, that `whatshap` normally adds to the file. Just to make sure I understood this correctly: The file "freebayes_raw_corr_potatov61.phased.vcf.gz" is the output of `whatshap polyphase`, right? If that is the case, this would explain why `haplotag` did not tag anything and that likely something went wrong with `polyphase`. If you like, you can send me the reference file as well then I can run it myself to check why it is not working.

**Comment by markopetek** [comment]
Thanks @eblerjana. I've checked my commands and realized I bgzipped by input vcf instead of the phased one. Now the haplotag worked:
```
Found 1 sample(s) in input VCF
Keeping 1 sample(s) for haplo-tagging
Found 1 sample(s) in BAM file
Reading alignments for sample 'samplix' and detecting alleles ...
Found 14699 reads covering 744 variants

== SUMMARY ==
Total alignments processed:                     31501
Alignments that could be tagged:                14230
Alignments spanning multiple phase sets:         8242
haplotag - total processing time: 2.3058791160583496
```
