### ISSUE TITLE
WhatsHap haplotag doesn't work on uncompressed vcf file

### ISSUE THREAD

**Issue by HJeffery** [whatshap/whatshap#312]
When running WhatsHap haplotag with the following command format:
whatshap haplotag -o output.bam --reference gch38.fasta SNPs.vcf sample.bam 

It produces the following summary:

Total alignments processed:                    625783
Alignments that could be tagged:                    0
Alignments spanning multiple phase sets:            0

There is no error but haplotag doesn't tag any reads when given an uncompressed vcf (I repeated it with a compressed vcf and it worked fine). Please may a warning/error be added, ideally also exiting the program, if an uncompressed vcf is given as an argument. This would save people time troubleshooting.

**Comment by ptrebert** [comment]
Yes, we can add this warning, or trigger an immediate exit. However, the command line help for the `haplotag` command is explicit:
```
VCF                   VCF file with phased variants (must be gzip-compressed
                        and indexed)
```
