### ISSUE TITLE
whatshap cannot run Deepvariant VCF file

### ISSUE THREAD

**Issue by B10inform** [whatshap/whatshap#322]
I am having error running deep-variant generated vcf file. **whatshap phase** works fine with deepvariant vcf file, but the vcf file generated from in this step does not work with whatshap haplotag.

**My command**
whatshap haplotag -o pa_ctg_bwa_HiFi_sorted_filtered_phase_haplotag.vcf --reference pa_ctg.fasta pa_ctg_bwa_HiFi_sorted_filtered_phase.vcf.gz pa_ctg_bwa_HiFi_sorted_filtered.bam

**Error:** 
Found 1 sample(s) in input VCF
Keeping 1 sample(s) for haplo-tagging
Found 0 sample(s) in BAM file
Traceback (most recent call last):
  File "/home/.local/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/home/.local/lib/python3.7/site-packages/whatshap/__main__.py", line 83, in main
    module.main(args)
  File "/home/.local/lib/python3.7/site-packages/whatshap/cli/haplotag.py", line 589, in main
    run_haplotag(**vars(args))
  File "/home/.local/lib/python3.7/site-packages/whatshap/cli/haplotag.py", line 478, in run_haplotag
    shared_samples = compute_shared_samples(bam_reader, ignore_read_groups, use_vcf_samples)
  File "/home/.local/lib/python3.7/site-packages/whatshap/cli/haplotag.py", line 325, in compute_shared_samples
    "No common samples between VCF and BAM file detected. "
ValueError: No common samples between VCF and BAM file detected. You may restart the analysis setting "--ignore-read-groups" (if appropriate) to avoid this error.

**Vcf file:**

**deepvariant **
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=RefCall,Description="Genotyping model thinks this site is reference.">
##FILTER=<ID=LowQual,Description="Confidence in this variant being real is below calling threshold.">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position (for use with symbolic alleles)">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Conditional genotype quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth">
##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum DP observed within the GVCF block.">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Read depth for each allele">
##FORMAT=<ID=VAF,Number=A,Type=Float,Description="Variant allele fractions.">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Phred-scaled genotype likelihoods rounded to the closest integer">
##DeepVariant_version=1.1.0
##contig=<ID=ptg000001l,length=179134>
##contig=<ID=ptg000002l,length=124340>
##contig=<ID=ptg000003l,length=36061850>
##contig=<ID=ptg000004l,length=3628562>
##contig=<ID=ptg000005l,length=52188020>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	default
ptg000002l	6707	.	AC	A	5	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:5:3:1,2:0.666667:3,0,14
ptg000002l	6713	.	CG	C	3.1	RefCall	.	GT:GQ:DP:AD:VAF:PL	./.:3:3:1,2:0.666667:0,0,6
ptg000002l	6732	.	CG	C	12.5	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:11:3:1,2:0.666667:12,0,16
ptg000002l	6737	.	GC	G	8.3	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:6:3:1,2:0.666667:6,0,7
ptg000002l	7005	.	GC	G	2	RefCall	.	GT:GQ:DP:AD:VAF:PL	./.:4:3:1,2:0.666667:0,4,7
ptg000002l	7033	.	GT	G	3.1	RefCall	.	GT:GQ:DP:AD:VAF:PL	./.:3:3:1,2:0.666667:0,2,3
ptg000002l	7363	.	GC	G	13.7	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:7:3:1,2:0.666667:12,0,7

** VCF file after whatshap **
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=RefCall,Description="Genotyping model thinks this site is reference.">
##FILTER=<ID=LowQual,Description="Confidence in this variant being real is below calling threshold.">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position (for use with symbolic alleles)">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Conditional genotype quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth">
##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum DP observed within the GVCF block.">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Read depth for each allele">
##FORMAT=<ID=VAF,Number=A,Type=Float,Description="Variant allele fractions.">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Phred-scaled genotype likelihoods rounded to the closest integer">
##DeepVariant_version=1.1.0
##contig=<ID=ptg000001l,length=179134>
##contig=<ID=ptg000002l,length=124340>
##contig=<ID=ptg000003l,length=36061850>
##contig=<ID=ptg000004l,length=3628562>
##contig=<ID=ptg000005l,length=52188020>
##commandline="(whatshap 1.1.dev91+gc714ed5) phase -o pa_ctg_bwa_HiFi_sorted_filtered_phase.vcf --reference pa_ctg.fasta pa_ctg_bwa_HiFi_sorted_filtered.vcf.gz pa_ctg_bwa_HiFi_sorted_filtered.bam"
##FORMAT=<ID=PS,Number=1,Type=Integer,Description="Phase set identifier">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	default
ptg000002l	6707	.	AC	A	5	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:5:3:1,2:0.666667:3,0,14
ptg000002l	6713	.	CG	C	3.1	RefCall	.	GT:GQ:DP:AD:VAF:PL	./.:3:3:1,2:0.666667:0,0,6
ptg000002l	6732	.	CG	C	12.5	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:11:3:1,2:0.666667:12,0,16
ptg000002l	6737	.	GC	G	8.3	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:6:3:1,2:0.666667:6,0,7
ptg000002l	7005	.	GC	G	2	RefCall	.	GT:GQ:DP:AD:VAF:PL	./.:4:3:1,2:0.666667:0,4,7
ptg000002l	7033	.	GT	G	3.1	RefCall	.	GT:GQ:DP:AD:VAF:PL	./.:3:3:1,2:0.666667:0,2,3
ptg000002l	7363	.	GC	G	13.7	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:7:3:1,2:0.666667:12,0,7
ptg000002l	7381	.	AG	A	14.9	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:14:3:1,2:0.666667:14,0,22

Best

**Comment by williamrowell** [comment]
I think this is the key part of the output to explain the error.

```Found 1 sample(s) in input VCF
Keeping 1 sample(s) for haplo-tagging
Found 0 sample(s) in BAM file```

`whatshap haplotag` is looking for the same sample to exist in the BAM and the VCF.  You can either add a read group to the BAM with the sample name from your vcf (`default`), or try the `whatshap haplotag --ignore-read-groups` parameter.

**Comment by kangxiongbin** [comment]
> 

I added the command "--ignore-read-groups". But when I generated the vcf file by freebayes,  encountering similar issue. How to add sample name to bam file or how to deal with the problem? 

**Command:**
freebayes -f scaffold_500.fa short.bam > var.vcf
samtools index short.bam
whatshap phase -o phased.vcf --reference scaffold_500.fa --ignore-read-groups var.vcf short.bam
bgzip phased.vcf
tabix phased.vcf.gz
whatshap haplotag -o haplotagged.bam --reference scaffold_500.fa phased.vcf.gz short.bam

**Issue:**
Found 1 samples in VCF file
Samples in BAM file:
ERROR: No common samples between VCF and BAM file. Aborting.

**Head of VCF:**
##fileformat=VCFv4.2
##fileDate=20220317
##source=freeBayes v1.3.5
##reference=scaffold_500.fa
##commandline="freebayes -f scaffold_500.fa short.bam"
##commandline="(whatshap 0.18) phase -o phased.vcf --reference scaffold_500.fa --ignore-read-groups var.vcf short.bam"
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##INFO=<ID=DPB,Number=1,Type=Float,Description="Total read depth per bp at the locus; bases in reads overlapping / bases in haplotype">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=RO,Number=1,Type=Integer,Description="Count of full observations of the reference haplotype.">
##INFO=<ID=AO,Number=A,Type=Integer,Description="Count of full observations of this alternate haplotype.">
##INFO=<ID=PRO,Number=1,Type=Float,Description="Reference allele observation count, with partial observations recorded fractionally">
##INFO=<ID=PAO,Number=A,Type=Float,Description="Alternate allele observations, with partial observations recorded fractionally">
##INFO=<ID=QR,Number=1,Type=Integer,Description="Reference allele quality sum in phred">
##INFO=<ID=QA,Number=A,Type=Integer,Description="Alternate allele quality sum in phred">
##INFO=<ID=PQR,Number=1,Type=Float,Description="Reference allele quality sum in phred for partial observations">
##INFO=<ID=PQA,Number=A,Type=Float,Description="Alternate allele quality sum in phred for partial observations">
##INFO=<ID=SRF,Number=1,Type=Integer,Description="Number of reference observations on the forward strand">
##INFO=<ID=SRR,Number=1,Type=Integer,Description="Number of reference observations on the reverse strand">
##INFO=<ID=SAF,Number=A,Type=Integer,Description="Number of alternate observations on the forward strand">
##INFO=<ID=SAR,Number=A,Type=Integer,Description="Number of alternate observations on the reverse strand">

**Comment by kangxiongbin** [comment]
When I add the RG in bam, it work. (run minimap2 of bwa add -R "@RG\\tID:foo\\tSM:sample")

**Comment by williamrowell** [comment]
That's definitely the best practice. DeepVariant and FreeBayes (and most variant callers) pull the sample name from the `@RG SM` header tag.

**Comment by marcelm** [comment]
This issue seems to have been resolved, closing it now.
