### ISSUE TITLE
Sex-specific recombination rates?

### ISSUE THREAD

**Issue by chlangley** [whatshap/whatshap#325]
I am wondering if there is any prospect of using the quantitatively more accurate sex-specific recombination maps (e.g., those from deCode) in a fork of whatshap or a future version.

Cursory examination of the of the sex-specific maps show large differences in the rates in male versus females.  This could lead to effectively filtered errors phasing/genotyping.  For example there are regions in which one sex shows not crossing over while the other has plenty.  The average would allow putative recombination when it should be filtered.  

General improvement in phasing may also appear in regions where the rates are not zero.

I know this sounds like a 'feature request' and that this forum is not the venue for such.  I don't have time right now to dig into the code and consider my own modification.  So this is just a effort to stimulate discussion and gather any relevant information.

Cheers,
Chuck

**Comment by tobiasmarschall** [comment]
Dear Chuck,

thanks for this input. This is an interesting feature request and this is absolutely the right venue for those. This would affect the very core of the DP algorithm, i.e. the information which parent is male/female would need to used there. I think it is conceptually easy, but practically a bit involved to implement. I'm leaving this here and would encourage others to comment -- if there is a demand for this feature we might implement it.

Best,
Tobias
