### ISSUE TITLE
whatshap: error: invalid choice: 'polyphase'

### ISSUE THREAD

**Issue by EDJONEILL** [whatshap/whatshap#326]
I have downloaded the current whatshap version (0.18) with conda. I tried to run whatshap polyphase using the command:

`whatshap polyphase -o output.vcf --reference=reference.fas input.vcf input.bam --ploidy 6 --ignore-read-groups`

This gave the error:

`usage: whatshap [-h] [--version] [--debug]
                {phase,stats,compare,hapcut2vcf,unphase,haplotag,genotype} ...

positional arguments:
  {phase,stats,compare,hapcut2vcf,unphase,haplotag,genotype}
    phase               Phase variants in a VCF with the WhatsHap algorithm
    stats               Print phasing statistics of a single VCF file
    compare             Compare two or more phasings
    hapcut2vcf          Convert hapCUT output format to VCF
    unphase             Remove phasing information from a VCF file
    haplotag            Tag reads by haplotype
    genotype            Genotype variants

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --debug               Print debug messages
whatshap: error: invalid choice: 'polyphase' (choose from 'phase', 'stats', 'compare', 'hapcut2vcf', 'unphase', 'haplotag', 'genotype')`

Is the polyphase command still supported? Am I doing something wrong here?

Thanks,
Ed

**Comment by ptrebert** [comment]
Hi Ed,
the `polyphase` command was added in v1.0, and v0.18 is not current. The bioconda channel has v1.1 listed when I search for `whatshap` as the most recent (=current) version. Can you install that and try again?
Best,
Peter

**Comment by EDJONEILL** [comment]
Hi Peter,
Thanks for your reply. I specified the version number to Conda and also used both the bioconda and conda-forge channels, which seems to have downloaded it properly.
Thanks,
Ed
