### ISSUE TITLE
Version 1.0 or 1.1 not installing?

### ISSUE THREAD

**Issue by Pharmacogenetecist** [whatshap/whatshap#331]
Trying to update to 1.0 or 1.1 via conda and unable to. Have tried uninstalling but still getting 0.18

**Comment by tobiasmarschall** [comment]
Maybe there are other packages in your environment such that not all dependencies can be met. I suggest you try installing WhatsHap into a new environment, e.g. `conda create -n whatshap whatshap`. Does that work?

**Comment by Pharmacogenetecist** [comment]
> Maybe there are other packages in your environment such that not all dependencies can be met. I suggest you try installing WhatsHap into a new environment, e.g. `conda create -n whatshap whatshap`. Does that work?

Unfortunately not - the above gave me a repo/channel error. I created a new environment and tried to install via conda install -c bioconda whatshap that installed 0.18. Tried updating - "all requested packages already installed".

Odd.

**Comment by tobiasmarschall** [comment]
Can you post this error message and possibly the output of `conda info`? To me this sounds more like a Conda issue than immediately related to WhatsHap.

**Comment by Pharmacogenetecist** [comment]
> Can you post this error message and possibly the output of `conda info`? To me this sounds more like a Conda issue than immediately related to WhatsHap.

$ conda create -n whatshap whatshap
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - whatshap

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by tobiasmarschall** [comment]
Looks like you are lacking Bioconda. https://bioconda.github.io/

**Comment by ptrebert** [comment]
I cannot reproduce the problem...

```
conda create -c bioconda -p ./testsetup whatshap
```
This installs whatshap v1.1 as expected

**Comment by Pharmacogenetecist** [comment]
Thank you all, that has resolved the issue.

**Comment by ptrebert** [comment]
Great, glad to hear that!
