### ISSUE TITLE
Feature request: add flag to ignore sample name when comparing single sample VCFs

### ISSUE THREAD

**Issue by williamrowell** [whatshap/whatshap#334]
Sometimes different names are used to describe the same sample (e.g. HG002 vs NA24385, HG001 vs NA12878), which requires one VCF to be reheadered before comparing.  It'd be nice to have a flag to override this behavior for single-sample VCFs when using `whatshap compare`.

**Comment by tobiasmarschall** [comment]
That's a great suggestion!
