### ISSUE TITLE
Conflicting output between `whatshap stat` and `whatshap phase`

### ISSUE THREAD

**Issue by evanbiederstedt** [whatshap/whatshap#341]
Hi there

Apologies, I'm having difficulty debugging some of the conflicting messages I get with the CLI. I've tried to isolate the behavior to a VCF file with one row, `example1.vcf`.

Here's `whatshap stats example1.vcf`:

```
Found 1 sample(s) in input VCF
Reporting results for sample "SAMPLE_NAME"
Phasing statistics for sample "SAMPLE_NAME" from file /path/example1.vcf
---------------- Chromosome chromosome_id ----------------
     Variants in VCF:        1
        Heterozygous:        1 (       0 SNVs)
              Phased:        0 (       0 SNVs)
            Unphased:        1 (not considered below)
          Singletons:        0 (not considered below)
              Blocks:        0

Block sizes (no. of variants)
   Median block size:         nan variants
  Average block size:         nan variants
       Largest block:        0    variants
      Smallest block:        0    variants

Block lengths (basepairs)
      Sum of lengths:        0    bp
 Median block length:         nan bp
Average block length:         nan bp
       Longest block:        0    bp
      Shortest block:        0    bp
           Block N50:      nan    bp
 ```
 
 There is clearly a HET SNV here. I can verify this with `bcftools view -g het /path/example1.vcf`. 
 
 
 
 However, when I run `whatshap phase` or `whatshap polyphase`, I get the following output:
 
 ```
 This is WhatsHap (polyploid) 1.1 running under Python 3.9.1
======== Working on chromosome 'chromosome_id'
---- Processing individual "SAMPLE_NAME"
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 0
Reading alignments and detecting alleles ...
Found 0 reads covering 0 variants
....
 ```

I'm having difficulty debugging as to why this behavior exists, as it appears to be a basic parsing error or perhaps an error in how I'm using WhatsHap.

Do you have recommendations how to debug this? Are there reasons why `Number of remaining heterozygous variants: 0` would be the result? What commands/checks could I run to figure out how to fix this?

Perhaps I hit a snag around here: https://github.com/whatshap/whatshap/blob/main/whatshap/cli/polyphase.py#L249

I'm happy to share the VCFs and BAMs if that is helpful.

Thank you for the help, and I appreciate your time + support. 

Best, Evan

CC @eblerjana @marcelm @tobiasmarschall

**Comment by marcelm** [comment]
Can you send, attach or paste the VCF inline in a comment? I think a dummy BAM file would be sufficient here for debugging, but while you’re at it, please also paste the BAM header (`samtools -H`).

**Comment by marcelm** [comment]
Ah, and it seems the heterozygous variant is not an SNV. Have you tried to use `--indels` with `polyphase`?

**Comment by evanbiederstedt** [comment]
So by default, no InDels are phased unless this flag is used:

```
--indels              Also phase indels (default: do not phase indels)
```

I think that's the source of my confusion, thank you. I somehow missed this---I appreciate your help @marcelm 

A related question I should ask (which maybe requires a new email thread):
Is there a recommended workflow if the VCF contains variants with multiple ALT alleles?

That is, a variant such as:

```
CHROM  POS  REF  ALT
1    42    A    C, T
```

Is there simply no support provided by WhatsHap, or should users perform something with the VCF in order to phase these variants?

**Comment by marcelm** [comment]
Regarding the latter question: This is tracked in #128

**Comment by schrins** [comment]
Concerning multi-allelic variants: There is currently no support in Whatshap for this, neither for phase nor for polyphase. For the latter I have it on my to-do list, but I cannot say when I will have the time to integrate it.
