### ISSUE TITLE
whatshap phase: Make --indels the default

### ISSUE THREAD

**Issue by marcelm** [whatshap/whatshap#346]
I suggest to enable indel phasing by default. The option doesn’t have the best name anyway (it also works with "complex" variants/MNPs). By instead adding an `--only-snvs` option, that naming issue would also be solved.

This may require bumping the version to 2.0.

**Comment by marcelm** [comment]
Ping @tobiasmarschall @schrins Do you have an opinion on this? The option seems to work well enough and I think WhatsHap should aim to give the best possible phasing "out of the box", i.e., without providing any extra command-line arguments.

Raising this again because of #468, where @Npaffen was apparently not aware that `--indels` exists.

**Comment by schrins** [comment]
I don't see any problems so far by including indels by default. Not knowing about this option indeed came up multiple times now.
