### ISSUE TITLE
Compilation error in C++ polyphase classes

### ISSUE THREAD

**Issue by schrins** [whatshap/whatshap#355]
I get compilation errors when trying to compile a freshly cloned repository on the main branch using `pip install -e .` in a freshly created conda environment

```
    In file included from src/polyphase/haplothreader.cpp:1:
    src/polyphase/haplothreader.h: In constructor ‘ClusterEntry::ClusterEntry()’:
    src/polyphase/haplothreader.h:194:16: error: ‘numeric_limits’ is not a member of ‘std’
      194 |     score(std::numeric_limits<Score>::infinity()),
          |                ^~~~~~~~~~~~~~
    src/polyphase/haplothreader.h:194:36: error: expected primary-expression before ‘>’ token
      194 |     score(std::numeric_limits<Score>::infinity()),
          |                                    ^
    src/polyphase/haplothreader.h:194:39: error: ‘::infinity’ has not been declared; did you mean ‘finite’?
      194 |     score(std::numeric_limits<Score>::infinity()),
          |                                       ^~~~~~~~
          |                                       finite
```
The issue seems to be that numeric limits are no longer automatically included, but require to have `#include <limits>` at the beginning of affected C++ header files. This might be similar to a previous pull request #299. When adding this line to `haplothreader.h` and `switchflipcalculator.h` everything seems to work.

Can anyone reproduce this and/or should I just open a pull request for this?

**Comment by marcelm** [comment]
I cannot reproduce it on Ubuntu 20.04 (and in a fresh Conda environment). Just open a PR, adding that #include is not going to break anything.

**Comment by marcelm** [comment]
I was able to reproduce it by using a Conda-installed compiler (`conda install gxx`). I will push a fix.
