### ISSUE TITLE
phase the long-read with copy number variation

### ISSUE THREAD

**Issue by charliechen912ilovbash** [whatshap/whatshap#361]
Dear whatshap teams,

I am trying to phase a human tumor sample, which contains copy number loss at some regions.
I called the SNP in the paired `normal` sample, then I tried two things:
(1) `whatshap phase` on `normal bam`, yielding the `normal phased vcf`, then `whatshap haplotag` on `tumor bam` with the `normal phased vcf`.
(2) `whatshap phase` on `tumor bam`, yielding the `tumor phased vcf`, then `whatshap haplotag` on `tumor bam` with the `tumor phased vcf`. 

I'm not sure which is correct.

In the result of (1), the ratio of phased SNP between H1 and H2 is around 1:1 anywhere, even in the copy number loss region, where H1/H2 should be closed to 1:0 or 0:1.
In the result of (2), the ratio of phased SNP between H1 and H2 is around 1:0 (or 0:1) anywhere, even in the non-copy number loss region, where H1/H2 should be 1:1.

The phased read count, read depth also closed to the H1/H2 ratio above.
According to #330 , maybe separately phasing on CNV and non-CNV region could be a way to resolve this problem?

**Comment by charliechen912ilovbash** [comment]
yes, (2) is the correct way to do it.

**Comment by eesiribloom** [comment]
Thanks! So you are using SNPs from normal tissue right? but then phasing with the tumor bam

**Comment by charliechen912ilovbash** [comment]
You're welcome! Yes.

**Comment by eesiribloom** [comment]
Hi @charliechen912ilovbash , could I ask how you determined that (2) is the correct way? @schrins suggests an alternative idea here #527 

Cheers

**Comment by charliechen912ilovbash** [comment]
Sorry for the misleading wording, I mean (2) seems more reasonable in my case. Since tumor sample contains a lot of CNV, allele frequency will then be abnormal, plus, somatic SNV is less than 1% of total SNV in my data. Also I have seen the same method in some cancer studies recently.

By the way, about c) in your post, since R10 flow cell, SNV accuracy is largely improved, if there is no Illumina data, I may consider using Nanopore data to call SNV with ClairS or Deepvariant, if there is enough depth in Nanopore data.

**Comment by ywzhang071394** [comment]
> Sorry for the misleading wording, I mean (2) seems more reasonable in my case. Since tumor sample contains a lot of CNV, allele frequency will then be abnormal, plus, somatic SNV is less than 1% of total SNV in my data. Also I have seen the same method in some cancer studies recently.
> 
> By the way, about c) in your post, since R10 flow cell, SNV accuracy is largely improved, if there is no Illumina data, I may consider using Nanopore data to call SNV with ClairS or Deepvariant, if there is enough depth in Nanopore data.

Hi @charliechen912ilovbash  Thank you for the nice information. I am wondering how you keep the haplotags comparable when you run whatshap separately for tumor and normal samples. For example, at the same loci, the normal reads may labelled as HP1 while the tumor reads may labelled as HP2. Also, could you share the studies using this strategy? Thank you!

**Comment by ywzhang071394** [comment]
> Sorry for the misleading wording, I mean (2) seems more reasonable in my case. Since tumor sample contains a lot of CNV, allele frequency will then be abnormal, plus, somatic SNV is less than 1% of total SNV in my data. Also I have seen the same method in some cancer studies recently.
> 
> By the way, about c) in your post, since R10 flow cell, SNV accuracy is largely improved, if there is no Illumina data, I may consider using Nanopore data to call SNV with ClairS or Deepvariant, if there is enough depth in Nanopore data.

Hi @charliechen912ilovbash Thank you for the nice information. According to my understanding, you used the same normal VCF to run whatshap seperately for normal and tumor files. Am I correct? I am wondering if the haplotags generated by this method are comparable between Normal and Tumor samples. For example, the same loci in tumor and normal samples should have the same haolotags. Is that possible the normal reads show HP1 and tumor reads show HP2?

**Comment by charliechen912ilovbash** [comment]
I call germline variants in the normal sample, then:
For tumor samples, 
    `whatshap phase` with these variants and tumor reads
    `whatshap haplotag` with the phased variants and tumor reads.
For normal samples, 
    `whatshap phase` with these variants and normal reads
    `whatshap haplotag` with the phased variants and normal reads.

Is that possible the normal reads show HP1 and tumor reads show HP2?
>> I think a somatic variant would make it possible. Which is only ~1% in my case. So it is kind of the balance between (1) phasing the somatic variants region and (2) the regions that are concordant between the tumor and the normal.
