### ISSUE TITLE
Phasing single sample Vs multi sample

### ISSUE THREAD

**Issue by ramesh8v** [whatshap/whatshap#365]
Hello,

I have 12 samples genotyped with ~100X Illumina reads and ~15X ONT reads. I used Illumina to call variants and used both Illumina and ONT reads to phase haplotypes. I phased each sample individually in 12 separate runs using a single-sample vcf file. My question is phasing all the samples together in a single run using a multi-sample vcf file have any advantages over phasing individual samples in separate runs? Although these samples are not family trios, I expect them to share haplotypes. Does Whatshap use haplotypes of one sample to stitch the haplotypes of other samples? I'd appreciate any pointers. Thanks!

**Comment by marcelm** [comment]
If you do not use `--ped` to specify family relationships, there is no advantage. WhatsHap phases the samples independently, so phasing them in separate runs should give the same results as phasing them one by one. Phasing samples individually of course has the advantage that you can do the phasing in parallel.

**Comment by ramesh8v** [comment]
Thank you!
