### ISSUE TITLE
Command for phasing Oxford Nanopore long-reads

### ISSUE THREAD

**Issue by liuyangzzu** [whatshap/whatshap#366]
Hi,
Would you please check if below command is ok for phasing Oxford Nanopore sequencing reads? Any long-read options needed? Thank you!

```
whatshap phase --ignore-read-groups \
    --reference ${referenceGenome} \
    -o ${phasingFile} \
    ${highQualityVCFFile}   ${bamFile}
```

**Comment by tobiasmarschall** [comment]
You don't need any specific parameters for long reads as WhatsHap automatically uses the most phase-informative reads available. So the command looks good.
