### ISSUE TITLE
Haplotag no ploidy

### ISSUE THREAD

**Issue by Guoshuai1314** [whatshap/whatshap#381]
Howdy!

I am using WHATshap to analyze polyploid data, and WHEN I run Haplotag I find that it can't handle polyploid data, there is no "--ploidy" parameter. The results of Haplotag are shown as diploids (H1 and H2).
Any ideas on how to fix?

Thanks.
ShuaiGuo

Whatshap version 1.5.dev24+g80266b3
Python 3.10.4
Pip

**Comment by parkgyuhwang** [comment]
Same problem.
Just H1, H2 and none.
