### ISSUE TITLE
question for --internal-downsampling  option in phase command

### ISSUE THREAD

**Issue by PengJia6** [whatshap/whatshap#393]
Hi,  

In default, whatshap will downsample the reads to 15X when phase the varaints. Does whatshap randomly select 15X reads or select the longest 15X reads for phasing? 

In other word, to obtain a longer phasing block, is it necessary to extract the longest 15X read from my bam file (50X) for phasing? 

Thnaks！

Peng Jia

**Comment by marcelm** [comment]
You should not need to change that parameter as WhatsHap uses the reads that are best suited for phasing. These will usually be long reads, but it will also choose shorter reads if they are necessary to bridge low-coverage regions.

See Section 2.2 in https://www.biorxiv.org/content/10.1101/085050v2 for a summary and [Selecting Reads for Haplotype Assembly](https://www.biorxiv.org/content/10.1101/046771v1) for the full description of the method.

**Comment by PengJia6** [comment]
Very clear statement, Thanks!
