### ISSUE TITLE
Polyphase Ploidy Level Troubleshoot

### ISSUE THREAD

**Issue by rmormando** [whatshap/whatshap#401]
I can't run my WhatsHap command because I keep getting this error message:

`ERROR: whatshap error: Inconsistent ploidy (4 and 2)`

I am running this command with:
`Python v3.9.13`
`WhatsHap v1.6`

And downloaded WhatsHap through conda:
`conda install whatshap`

This is the command I am trying to run:
`whatshap polyphase --ploidy 4 -o /PATH/phased.vcf --reference=/PATH/s288c.fa /PATH/shortreads.vcf /PATH/longreads.bam --ignore-read-groups --block-cut-sensitivity 1 --indels`

I followed the "reccomended workflow" on the documentation site:
1. aligned the reads with minimap2
2. converted to BAM file with SAMtools (along with sorting and indexing)
3. did variant calling through FreeBayes to get a VCF file

My long reads come from PacBio HiFi sequencing and the short reads come from Illumina sequencing. I used the short reads with FreeBayes to get the VCF file and got the BAM file from the minimap2 alignment using the long reads. I am only using one sample  with this command and it's a tetraploid yeast genome so I'm not sure where the error message is seeing a ploidy of 2.

If someone could help me understand what the error message means and how to work around it that would be great! If any other information is needed please let me know! Thanks!

**Comment by rmormando** [comment]
I FIXED THIS! It was a problem with FreeBayes!

**Comment by marcelm** [comment]
Great! Can you let us know what the problem was? This may help other users in the future!
