### ISSUE TITLE
Development instructions outdated, tox does not build anymore

### ISSUE THREAD

**Issue by schrins** [whatshap/whatshap#420]
I realized that the instructions for a conda environment for developers is outdates, as it still recommends Python 3.6, which is officially not supported anymore. https://whatshap.readthedocs.io/en/latest/develop.html

Furthermore, I ran into trouble building a conda environment that passes the automated tests. From the docs I just changed the python version to 3.7 (and 3.9 in a second attempt):

`mamba create -n whtest python=3.7 pysam PyVCF pyfaidx xopen Cython pytest sphinx-issues -c bioconda`
(I use mamba instead of conda, a wrapper that resolves dependencies much quicker)

When compiling, pip installs the additional packages `networkx-2.6.3` `pulp-2.7.0` `pysam-0.20.0` `scipy-1.7.3`. The compilation works and whatshap is runnable, but we might consider to include these packages into the conda command and specifiy `pysam>=0.18` as well, because for Python 3.7 conda installs `pysam-0.16.0` per default for some reason. Or maybe even directly go to something like Python 3.9 (which installs `pysam-0.20.0` directly).

---------------------

**Now some issue:** When running `tox -e py37` (or `py39` for the second attempt), pyfaidx fails to build for some reason (see long paste below). I might experiment with this further to see if I can find any incompatibilities between the packages. For Python 3.9 the error is basically the same. There might be a second issue with `pulp`, where the some test cases fail on the test server, even though everything compiles fine on my system (on branch `hybrid-polyphase`). But in order to reproduce this locally, I first need to fix the build issue with tox.

```
(whtest) sven@CarbonMachine:~/workspace/whatshap/whatshap-test/whatshap$ tox -e py37
py37 create: /home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37
py37 installdeps: pytest, Cython>=0.29.17
py37 develop-inst: /home/sven/workspace/whatshap/whatshap-test/whatshap
ERROR: invocation failed (exit code 1), logfile: /home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/log/py37-2.log
======================================================================================================================================= log start ========================================================================================================================================
Obtaining file:///home/sven/workspace/whatshap/whatshap-test/whatshap
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Collecting pyfaidx>=0.5.5.2
  Using cached pyfaidx-0.7.1.tar.gz (103 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pulp>=2
  Using cached PuLP-2.7.0-py3-none-any.whl (14.3 MB)
Collecting pysam>=0.18.0
  Using cached pysam-0.20.0-cp37-cp37m-manylinux_2_24_x86_64.whl (15.4 MB)
Collecting networkx
  Using cached networkx-2.6.3-py3-none-any.whl (1.9 MB)
Collecting scipy
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Collecting biopython>=1.73
  Using cached biopython-1.80-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
Collecting xopen>=1.2.0
  Using cached xopen-1.7.0-py3-none-any.whl (15 kB)
Collecting numpy
  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Requirement already satisfied: setuptools>=0.7 in ./.tox/py37/lib/python3.7/site-packages (from pyfaidx>=0.5.5.2->whatshap==1.7.dev123+g30a03ad) (59.6.0)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: typing-extensions in ./.tox/py37/lib/python3.7/site-packages (from xopen>=1.2.0->whatshap==1.7.dev123+g30a03ad) (4.4.0)
Collecting isal>=1.0.0
  Using cached isal-1.1.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (281 kB)
Building wheels for collected packages: whatshap, pyfaidx
  Building editable for whatshap (pyproject.toml): started
  Building editable for whatshap (pyproject.toml): still running...
  Building editable for whatshap (pyproject.toml): finished with status 'done'
  Created wheel for whatshap: filename=whatshap-1.7.dev123+g30a03ad-0.editable-cp37-cp37m-linux_x86_64.whl size=5159 sha256=34370d0acaf91f469aa5443db786ce4bc46023db01268dd9a0a393f38309f90d
  Stored in directory: /tmp/pip-ephem-wheel-cache-zsov3ien/wheels/e0/64/51/ba412c928fa39382fb8d139557e81b64c014e27b83df270ff3
  Building wheel for pyfaidx (setup.py): started
  Building wheel for pyfaidx (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      /home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        SetuptoolsDeprecationWarning,
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/pyfaidx
      copying pyfaidx/cli.py -> build/lib/pyfaidx
      copying pyfaidx/__init__.py -> build/lib/pyfaidx
      /home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-o3fhyiom/pyfaidx_56073a9e7dbc44319abdffd31a652501/setup.py", line 37, in <module>
          "Topic :: Scientific/Engineering :: Bio-Informatics"
        File "/home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/command/install.py", line 557, in run
          self.run_command(cmd_name)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/dist.py", line 984, in run_command
          cmd_obj.ensure_finalized()
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyfaidx
  Running setup.py clean for pyfaidx
Successfully built whatshap
Failed to build pyfaidx
Installing collected packages: pysam, pulp, six, numpy, networkx, isal, xopen, scipy, pyfaidx, biopython, whatshap
  Running setup.py install for pyfaidx: started
  Running setup.py install for pyfaidx: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyfaidx did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      /home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        SetuptoolsDeprecationWarning,
      running install
      /home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/pyfaidx
      copying pyfaidx/cli.py -> build/lib/pyfaidx
      copying pyfaidx/__init__.py -> build/lib/pyfaidx
      running install_lib
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-o3fhyiom/pyfaidx_56073a9e7dbc44319abdffd31a652501/setup.py", line 37, in <module>
          "Topic :: Scientific/Engineering :: Bio-Informatics"
        File "/home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/command/install.py", line 557, in run
          self.run_command(cmd_name)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/dist.py", line 984, in run_command
          cmd_obj.ensure_finalized()
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
        File "/home/sven/mambaforge/envs/whtest/lib/python3.7/distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyfaidx

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

======================================================================================================================================== log end =========================================================================================================================================
________________________________________________________________________________________________________________________________________ summary _________________________________________________________________________________________________________________________________________
ERROR:   py37: InvocationError for command /home/sven/workspace/whatshap/whatshap-test/whatshap/.tox/py37/bin/python -m pip install --exists-action w -e . (exited with code 1)
```

**Comment by marcelm** [comment]
I’ll read the rest later, but want to reply to this:
> mamba create -n whtest python=3.7 pysam PyVCF pyfaidx xopen Cython pytest sphinx-issues -c bioconda

Just providing `-c bioconda` does not work in general. If it works, it is an accident, but Bioconda requires that you configure conda-forge as well. I recommend that you just [run the recommended configuration instructions](https://bioconda.github.io/#usage). Also, remove `r` from your `~/.condarc` in case you have followed previous Bioconda installation instructions. The `r` channel is outdated (R packages are now in conda-forge). If you do not want to modify your channel list permanently, click on the "What if I don't want to modify my condarc?" triangle on the linked page.

**Comment by marcelm** [comment]
> When compiling, pip installs the additional packages `networkx-2.6.3` `pulp-2.7.0` `pysam-0.20.0` `scipy-1.7.3`. The compilation works and whatshap is runnable, but we might consider to include these packages into the conda command and specifiy `pysam>=0.18` as well, because for Python 3.7 conda installs `pysam-0.16.0` per default for some reason. Or maybe even directly go to something like Python 3.9 (which installs `pysam-0.20.0` directly).
 
I wonder whether we need to keep the Conda section at all. We could fix it by adding the list of dependencies to an `environment.yml` file and describing the appropriate `conda` command to install from that. However, we would need to keep that synchronized with the main list of dependencies in `setup.py`, which I don’t want to have to do.

I think the section is about somehow getting Python in the desired version, so we could just remove all dependencies except Python from the `conda install` command. Then the `pip install` step takes care of the remaining dependencies. This hybrid setup may feel a bit weird, but I think it is ok for a developer install.

Regarding your error message, I have searched a bit, but could only find some indication that it may have to do with an outdated setuptools. Maybe you can update that before running tox?

Are you on Ubuntu/Kubuntu? Then you could do what I do and use [the instructions for deadsnakes](https://whatshap.readthedocs.io/en/latest/develop.html#installing-other-python-versions-in-ubuntu). Then you would run (roughly) `apt install python3.7-dev python3.8-dev python3.9-dev python3.10-dev` and can do the rest with virtual environments, no Conda.

I use Conda all the time, but for this, it doesn’t seem to be a good fit because `tox` needs access to all the Python versions it is supposed to test for simultaneously, and with Conda, you can only have one Python version in a single Conda environment.

**Comment by schrins** [comment]
Update:
1. Indeed, conda-forge is already in the channels list because of mambaforge. I added bioconda a strict, correct ordering, but this did not change anything.
2. I am aware that conda does not support multiple python versions, but tox should at least work for the one version installed in the current environment.
3. I independently ran into setuptools being the potential cause. And indeed, the version used (59.6.0) is outdated and known to cause issues. However, I was unable to get rid of this version even after removing it from pip, conda and manually deleting all locations were this could be installed or cached. What solved the problem was to add a requirement to `setup.py` with `setuptools>=60`. This is of course temporary, but it proofs that the issue comes from some "phantom setuptools version" somewhere on my system which is always used over anything I install via conda or pip.

Regarding the dev description in the docs: I don't mind dropping all the packages from the list and let pip resolve the dependencies. I just tested this and it worked with just a python version.

**Comment by schrins** [comment]
It is very strange. There is definitely no cached setuptools-version below 60 anywhere on my system, except for some snap folders of other applications (I can obviously not delete them, but I would be highly surprised if tox touched these) or places that are not accessible without root privileges. I can also run `pip install -e .` perfectly fine and it will use the exact same versions that I see using `pip show <package>`. However, when executing `tox -e py37` it creates package folders in `.tox/py37/lib/python3.7/site-packages` (and also in `~/.local/share/virtualenv/wheel/3.7/image/1/CopyPipInstall`) where it uses older versions of certain packages, namely  `pip-22.2`, `setuptools-59.6.0` and `wheel-0.37.1` even though when using `pip show` I get the versions `22.3.1`, `´65.5.1` and `0.38.4` respectively in a newly created conda environment. I can of course add additional dependencies to make tox use newer versions which then work fine. But I'm puzzled how and why it uses these old versions anyways.

**Comment by schrins** [comment]
I made another attempt and now it worked. Order:
1. create conda environment
2. install `virtualenv` and `tox `manually via pip (in this order)
3. run `pip install -e .`
4. run `tox -e py37`

I guess this part is resolved for now. I hope this is useful for anyone who might have such an issue in the future. Only thing that remains then is to update the docs. Since I used an "empty" conda environment successfully now, we should also use this for the docs.

**Comment by marcelm** [comment]
Hm, I wonder whether your observations could be explained by the isolated build logic (PEP 518) that `pip install` applies because we have a `pyproject.toml` with a `[build-system]` key. If that exists (and I remember correctly), then `pip install` creates an *additional*, temporary virtual environment where it installs the given dependencies. We currently specify `setuptools>=43` in `pyproject.toml`, so if for some reason, setuptools 59 is available within that temporary environment (maybe from one of these wheel caches? no idea), you would run into the problem but you would never actually be able to observe that virtual environment because it exists only temporarily.

I tried to reproduce your problem, but wasn’t able to. I think we should just bump our minimum setuptools version in `pyproject.toml` just in case. It’s not a problem to require a relatively recent version because it just gets downloaded at install time if necessary, and it doesn’t need to be on the system (same for Cython, for example).
