### ISSUE TITLE
Whatshap polyphase on INDELs not working?

### ISSUE THREAD

**Issue by Coryza** [whatshap/whatshap#427]
Hi,

I'm running Whatshap polyphase (latest version) on a VCF file generated with Freebayes;
whatshap polyphase genome.vcf genome.bam --ploidy 3 --ignore-read-groups **--indels** --mapping-quality 0 --reference genome.fasta

Interestingly, I observe that no INDELs have been phased. After haplotagging I can manually clearly observe dozens of examples where INDELs are present in 1 haplotype but not in the other. What am I overlooking? 
```

grep -c '^[^#]' genome.vcf
40768
grep -c '|' genome.vcf
7882
grep '|' genome.vcf | awk '{print $4}' | sort | uniq -c
1782 A
2162 C
2197 G
1741 T
```

![polyphase](https://user-images.githubusercontent.com/7194842/210248187-808cf23f-c3db-4531-8177-7b6d6c261299.png)
_INDELs observed in the visualization are present in the VCF, unphased_

**Comment by Coryza** [comment]
Similar issue to #370?

**Comment by Coryza** [comment]
Upon converting MNP to SNP's / simplified INDELs with vcfallelicprimitives all SNPs are properly phased, INDELS (e.g. GA>A) are still not phased.

**Comment by schrins** [comment]
Hi,

I totally overlooked this issue. On first sight everything looks fine from your side. The polyploid phaser is oblivious to the variant type, because it only "sees" which read has which allele (0, 1, ...) for which variant position. This means, there must be an issue with the allele detection before. What happens if you leave out the `--reference` argument? This influences allele detection, because instead of deriving the alleles of each read from the cigar string only, it would additionally do some partial realignments to improve allele detection (hence the need of a reference genome). From experience this does not always lead to better results for non-human reference genomes.

If this does not help, would it be possible to share a small part of the problematic dataset? It would only need to contain one of two indel variants, so I can reproduce the bug and try to track it down with debug outputs.

**Comment by Coryza** [comment]
Unfortunately my VCF file is huge and therefore still contains a small amount of non-decomposed MNPs - which then crashes upon providing no reference;

```
whatshap polyphase tmp.vcf Cavendish.reads.bam --ploidy 3 --ignore-read-groups --indels --mapping-quality 0 > tmp.phase.vcf
This is WhatsHap (polyploid) 1.7 running under Python 3.8.10
======== Working on chromosome 'Chr00'
---- Processing individual unknown
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 12922
Skipped a deletion overlapping another variant at pos. 5994356
Skipped a deletion overlapping another variant at pos. 5994356
Skipped a deletion overlapping another variant at pos. 5994356
Skipped a deletion overlapping another variant at pos. 5994356
Skipped a deletion overlapping another variant at pos. 5994356
Skipped a deletion overlapping another variant at pos. 5994356
...
...
...
ValueError: The variant at position 12867193 (TTAAGAAATTTAGAGATCACGTATTTGCCAAATCATTCTCCAAATACTAAAGTCGAACCATATTCTTTTTGTTTGAGTAATGCATTAAAAGTGATCCAATTCTCTGAAGTTGATTTGTAACAAATAATGTGTTTAAAGAGATGAGAAATATATCTCTTTTATACAAATTTAATCTTTGCATTTAAAGTCCTCCAACTCTTCATGGCGCCTCCATCTATAGCATATGGTGTTGTTGTTGCATTACCACCATTTACATCCCATAGATCTTCTCCTATGAGATAAAACTTCAAATAAATTTTTTAGATCTTGTAGTTAGACTAATTGAAAAGTTCAATACTAACACAACTATAATATTTC -> CTAAAAATG) cannot be processed by the --no-reference allele detector. A reference sequence is needed.
```

I then continued by editing the code to simply not raise a ValueError, but continue processing - this completed without further issues, however INDELs remain unphased;
grep "|" tmp.phase.vcf | awk 'length($5) == 1' | wc -l
163545
grep "|" tmp.phase.vcf | awk 'length($5) >1' | wc -l
0

The data that I'm working on is proprietary, so I can't share (a subset of) the reference genome. But at least, here's a couple of examples of my VCF.

```
Chr01  3048181 .       TC      T       137.799 .       AB=0.117647;ABP=89.3583;AC=1;AF=0.333333;AN=3;AO=8;CIGAR=1X3M1X1M1X1M1X3M1X1M1X1M2X1M2X2M1X2M1X;DP=68;DPB=67.5556;DPRA=0;EPP=7.35324;EPPR=3.64073;GTI=0;LEN=1;MEANALT=22;MQM=44.875;MQMR=37.4839;NS=1;NUMALT=2;ODDS=0.266589;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=380;QR=1211;RO=31;RPL=8;RPP=20.3821;RPPR=4.76149;RPR=0;RUN=1;SAF=2;SAP=7.35324;SAR=6;SRF=15;SRP=3.08035;SRR=16;TYPE=del   GT:DP:AD:RO:QR:AO:QA 0/0/1:68:31,8,9:31:1211:8,9:380,258
Chr01  3048220 .       GC      G       43.654  .       AB=0.134328;ABP=80.8268;AC=1;AF=0.333333;AN=3;AO=9;CIGAR=1M1D1X;DP=67;DPB=66;DPRA=0;EPP=9.04217;EPPR=3.37904;GTI=0;LEN=1;MEANALT=5;MQM=40;MQMR=32.1509;NS=1;NUMALT=1;ODDS=10.0517;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=458;QR=1995;RO=53;RPL=9;RPP=22.5536;RPPR=4.03458;RPR=0;RUN=1;SAF=2;SAP=9.04217;SAR=7;SRF=26;SRP=3.05127;SRR=27;TYPE=del      GT:DP:AD:RO:QR:AO:QA    0/0/1:67:53,9:53:1995:9:458
Chr01  3048233 .       TA      T       4.0276  .       AB=0.106061;ABP=91.9749;AC=1;AF=0.333333;AN=3;AO=7;CIGAR=2X1M2I2M1X1M1D1M2X;DP=66;DPB=66.6364;DPRA=0;EPP=10.7656;EPPR=4.07475;GTI=0;LEN=1;MEANALT=9;MQM=41;MQMR=31.9216;NS=1;NUMALT=1;ODDS=0.423894;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=330;QR=1892;RO=51;RPL=7;RPP=18.2106;RPPR=3.3935;RPR=0;RUN=1;SAF=1;SAP=10.7656;SAR=6;SRF=22;SRP=5.09662;SRR=29;TYPE=del     GT:DP:AD:RO:QR:AO:QA    0/0/1:66:51,7:51:1892:7:330
Chr01  3048252 .       G       GATAGTCTCA      5.11197 .       AB=0.109375;ABP=87.8334;AC=1;AF=0.333333;AN=3;AO=7;CIGAR=1M9I3M1I2M1X2M1I1M2D3M;DP=64;DPB=68.2;DPRA=0;EPP=10.7656;EPPR=3.70517;GTI=0;LEN=9;MEANALT=7;MQM=41;MQMR=35.04;NS=1;NUMALT=1;ODDS=0.808648;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=263;QR=2041;RO=50;RPL=7;RPP=18.2106;RPPR=3.0103;RPR=0;RUN=1;SAF=1;SAP=10.7656;SAR=6;SRF=26;SRP=3.18402;SRR=24;TYPE=ins      GT:DP:AD:RO:QR:AO:QA0/0/1:64:50,7:50:2041:7:263
Chr01  3048255 .       T       TG      5.11197 .       AB=0.109375;ABP=87.8334;AC=1;AF=0.333333;AN=3;AO=7;CIGAR=1M9I3M1I2M1X2M1I1M2D3M;DP=64;DPB=68.2;DPRA=0;EPP=10.7656;EPPR=3.70517;GTI=0;LEN=1;MEANALT=7;MQM=41;MQMR=35.04;NS=1;NUMALT=1;ODDS=0.808648;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=263;QR=2041;RO=50;RPL=7;RPP=18.2106;RPPR=3.0103;RPR=0;RUN=1;SAF=1;SAP=10.7656;SAR=6;SRF=26;SRP=3.18402;SRR=24;TYPE=ins      GT:DP:AD:RO:QR:AO:QA    0/0/1:64:50,7:50:2041:7:263
Chr01  3048260 .       A       AT      5.11197 .       AB=0.109375;ABP=87.8334;AC=1;AF=0.333333;AN=3;AO=7;CIGAR=1M9I3M1I2M1X2M1I1M2D3M;DP=64;DPB=68.2;DPRA=0;EPP=10.7656;EPPR=3.70517;GTI=0;LEN=1;MEANALT=7;MQM=41;MQMR=35.04;NS=1;NUMALT=1;ODDS=0.808648;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=263;QR=2041;RO=50;RPL=7;RPP=18.2106;RPPR=3.0103;RPR=0;RUN=1;SAF=1;SAP=10.7656;SAR=6;SRF=26;SRP=3.18402;SRR=24;TYPE=ins      GT:DP:AD:RO:QR:AO:QA    0/0/1:64:50,7:50:2041:7:263
Chr01  3048261 .       CAA     C       5.11197 .       AB=0.109375;ABP=87.8334;AC=1;AF=0.333333;AN=3;AO=7;CIGAR=1M9I3M1I2M1X2M1I1M2D3M;DP=64;DPB=68.2;DPRA=0;EPP=10.7656;EPPR=3.70517;GTI=0;LEN=2;MEANALT=7;MQM=41;MQMR=35.04;NS=1;NUMALT=1;ODDS=0.808648;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=263;QR=2041;RO=50;RPL=7;RPP=18.2106;RPPR=3.0103;RPR=0;RUN=1;SAF=1;SAP=10.7656;SAR=6;SRF=26;SRP=3.18402;SRR=24;TYPE=del      GT:DP:AD:RO:QR:AO:QA    0/0/1:64:50,7:50:2041:7:263
Chr01  3048276 .       AG      A       46.2827 .       AB=0.107692;ABP=89.9026;AC=1;AF=0.333333;AN=3;AO=7;CIGAR=1M1I3M1D2M1X1M1X1M1X1M1X1M3I1X;DP=65;DPB=66.375;DPRA=0;EPP=5.80219;EPPR=3.48696;GTI=0;LEN=1;MEANALT=16;MQM=44.8571;MQMR=33.1463;NS=1;NUMALT=1;ODDS=10.657;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=270;QR=1486;RO=41;RPL=7;RPP=18.2106;RPPR=5.60547;RPR=0;RUN=1;SAF=2;SAP=5.80219;SAR=5;SRF=19;SRP=3.48696;SRR=22;TYPE=del     GT:DP:AD:RO:QR:AO:QA 0/0/1:65:41,7:41:1486:7:270
```

**Comment by Coryza** [comment]
Here another screenshot that - to me - clearly indicates INDELs that could be phased.

![Example](https://user-images.githubusercontent.com/7194842/213663535-5f087858-6bba-4c97-85bf-ae866707e464.png)

**Comment by schrins** [comment]
I might have found the issue: The --indel flag is not passed to the VCF writer. Thus, the indels are phased but the results are not written. If you did some code change already, could you try to change the call in `whatshap/cli/polyphase` line 106 from

```
                PhasedVcfWriter(
                    command_line=command_line,
                    in_path=variant_file,
                    out_file=output,
                    tag=tag,
                    ploidy=ploidy,
                    include_haploid_sets=include_haploid_sets,
                )
```

to

```
                PhasedVcfWriter(
                    command_line=command_line,
                    in_path=variant_file,
                    out_file=output,
                    tag=tag,
                    ploidy=ploidy,
                    indels=indels,
                    include_haploid_sets=include_haploid_sets,
                )
```

Regarding the other error message that some alleles cannot be detected without reference: This is caused by a substitution variant that is neither a SNP nor a true insertion or deletion. Although, I would say it is safe to just skip these variants (maybe with some warning) instead of stopping the entire program. Was there some reason to not skip these variants @marcelm ?

**Comment by Coryza** [comment]
Well that was an easy fix. 
grep "|" tmp.phase.vcf | awk 'length($5) == 1' | wc -l
175476
grep "|" tmp.phase.vcf | awk 'length($5) > 1' | wc -l
11304

Resolved! :-)

**Comment by schrins** [comment]
For now, we would rather skip MNPs, because there are still pending issues with the allele detection (#103 , #128 ). Especially the overlapping variants require some rewriting. If detecting MNPs is feasible in this context, I would add them.
