### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by sjclare** [whatshap/whatshap#451]
Hey,

Hope this isn't a dumb issue but I can't seem to figure it out. Whenever I install whatshap using either

`conda install -c bioconda whatshap` or 
`conda install -c "bioconda/label/cf201901" whatshap` or
`conda install -c "bioconda/label/main" whatshap`

it only installs version 0.18, rather than 1.7. I trying to install in its own self contained environment so there's no conflicts.

Thanks for any help

**Comment by marcelm** [comment]
@schrins is correct: Only using `-c bioconda` is not sufficient. This could be the problem. Please see the [Bioconda setup instructions](http://bioconda.github.io/#usage). If you do not want to add the Bioconda and conda-forge channels permanently to your channel list, see also [these instructions](http://bioconda.github.io/#do-not-modify-condarc) for how to specify them on the command line.

I have tried to clarify this in the documentation a bit. I admit it is a bit unfortunate that every user has to remember to do this.

**Comment by sjclare** [comment]
Thanks, I added `-c conda-fogre` and it's now installed. Thank you very much for your help :)

**Comment by marcelm** [comment]
Great you got it working!
