### ISSUE TITLE
Errors when using "phasing pedigrees" 

### ISSUE THREAD

**Issue by oceancongliu** [whatshap/whatshap#452]
hi,
I met a problem that i do not konw how to solve?
My main point of analysis was to phase sequencing reads from PB seq II ,this high-through data is F1 strain, i also sequenced parent data(illumin PE150). Firstly, i used F1.ccs.bam mapped to my genome using pbmm2 with default  parameter, the align.bam file was generated as inputbam. Next, I performed GATK4 to call SNV (snp and indel) using parent sequencing data,the standard VCF file was got as  input.vcf, including paternal and maternal  genotype.
![1](https://user-images.githubusercontent.com/130651170/232794018-5f475082-07c3-4e20-81f1-b554472f42e4.PNG)
Based the description of whatshap, "phasing pedigrees" may be useful to help. So,I prepared pedigree.ped file :
```
# Fields: family, individual_id, paternal_id, maternal_id, sex, phenotype
FAMILY01	b453667d	pat	mat	0	1
```
this is my input.bam file
![2](https://user-images.githubusercontent.com/130651170/232800578-d4363485-361e-4251-a336-2740b8e19a01.PNG)
![3](https://user-images.githubusercontent.com/130651170/232800766-83474aed-e466-4e7e-a792-b063b9e5eb17.PNG)

Then performed 
``
whatshap phase --ped pedigree.ped --reference=reference.fasta -o phased.vcf  input.vcf input.bam
``
A  error messages likes this, and the SNV was not phased .
```
WARNING: Relationship b453667d/mat/pat ignored because at least one of the individuals was not given by --samples. Hiding further warnings of this type, use --debug to show
Working on 2 samples from 2 families

# Working on contig chr01 in individual mat
Found 138264 usable heterozygous variants (381 skipped due to missing genotypes)
WARNING: Sample 'mat' not found in any BAM/CRAM file.
Found 0 reads covering 0 variants
Kept 0 reads that cover at least two variants each
Selected 0 most phase-informative reads covering 0 variants
Best-case phasing would result in 0 non-singleton phased blocks (0 singletons).
Phasing 1 sample by solving the MEC problem ...
No. of phased blocks: 0
```
My confused points :
1.How do i prepare correct input file?
2. Is the  individual_id  (b453667d)？ i got this ID from "RG:Z:b453667d"  of aligm.bam.
3.Whether F1 generation also needs variation information in input.vcf ?
4.Is there a better tool  that can help me with my analysis ? 
thanks.

**Comment by oceancongliu** [comment]
@schrins Thank you for your quickly reply.However, your general reply don't solve my confusion fully. For trio, the BAM file contains child information, the VCF file contains two parent sample's SNV. I guess that some problems may be occur in pedigree.ped file or SM tag. Can you give me other suggestions to help me figure it out?
I will preciate it.
Thanks.

**Comment by tobiasmarschall** [comment]
@oceancongliu In order to use pedigree phasing, you need (at least) a trio in the VCF. Only representing the two parents is not enough. WhatsHap needs to be able to match the sample names between VCF and BAM. Maybe this is helpful to you: https://doi.org/10.1007/978-1-0716-2819-5_8

**Comment by oceancongliu** [comment]
> 
Thanks for your help, I will reads this protocol carefully and try again with trio VCF (including two parents ad one child).
Actually, I am also confused with the sample names. In my BAM file (Paobio data) only contains the child sample name, without two parents sample names. As your mentioned: WhatsHap needs to be able to match the sample names between VCF and BAM. Is it necessary contain the parent SM in the BAM file? If your answer is yes, how do i solve the this problems that no two parents sample names in BAM file.
Look forward  to your reply.
Appreciate it.

**Comment by tobiasmarschall** [comment]
Yes, then you should prepare a BAM file where the read group has the `SM` field with the child sample name, which should match the exact name of the child sample in the VCF. That there's no reads for the parents in the BAM file is not an issue. WhatsHap will automatically do the right thing and combine the information from the child reads with the pedigree information to phase the whole trio. I'll close this for now. Feel free to re-open if you are still facing problems.

**Comment by oceancongliu** [comment]
Thanks for you suggestion, I have tagged BAM file with HP:Z:1 and HP:Z:2 tag. So, other question is that which one is belong to the paternal or maternal. What the relationship between HP:Z and genotype of child ? thanks.
