### ISSUE TITLE
AD (Allelic Depth) Array order of phased Variant Calls

### ISSUE THREAD

**Issue by justin-greenblatt** [whatshap/whatshap#467]
I am working with a VCF file that was generated using deepvariant and whatshap:

My question is: Does the array for AD (Allelic Depth) follow the same order of the alleles presented in GT? For example. I have 5 reads with reference allele and 10 reads with alternative allele. If my entry has a GT value of "0|1" I would expect my AD value to be equal to "5,10". And if GT="1|0", then AD="10,5" ? Or Does GT not affect the order of AD?

Couldn't find anything in the documentation confirming this.
 
EXAMPLE VCF FILE:
##DeepVariant_version=1.3.0
##commandline="(whatshap 1.0) phase --indels --chromosome chr1 --output samples/my_sample/whatshap/my_sample.GRCh38.regions/my_sample.GRCh38.chr1.deepvariant.phased.vcf.gz --reference reference/human_GRCh38_no_alt_analysis_set.fasta samples/my_sample/whatshap/my_sample.GRCh38.regions/my_sample.GRCh38.chr1.deepvariant.vcf.gz samples/my_sample/aligned/m54086U_220108_190007.GRCh38.bam"

chr1    21419   .       C       T       9.9     PASS    .       GT:GQ:DP:AD:VAF:PL:PS   1|0:9:6:4,2:0.333333:9,0,16:13301
chr1    21580   .       C       T       9.3     PASS    .       GT:GQ:DP:AD:VAF:PL:PS   0|1:8:6:2,4:0.666667:8,0,12:13301

Thanks

**Comment by schrins** [comment]
From my understanding, the AD field lists the allele depths in the order of allele names. The first value is always the reference allele count (allele "0"), the second is the alternative allele count (allele "1"), and the second, third, etc. alt alleles. It definitely does not depend on the GT field. For that reason whatshap never changes the content of the AD field.

**Comment by schrins** [comment]
Closing for now, as all questions seem to be answered. Feel free to re-open for further discussion.
