### ISSUE TITLE
No output from WhatsHap

### ISSUE THREAD

**Issue by suvi93** [whatshap/whatshap#474]
Hey, I'm using WhatsHap version 1.7 and this is the command i'm using - 

`whatshap phase -o out.vcf --reference=ref.fasta --indels in.vcf in.bam`

it seems to be running forever and the output file is not being written. how long does it usually take to run phasing for 1 sample? am I going wrong somewhere here? there is no error being written into the error file and it just says working on chr1.

**Comment by schrins** [comment]
Is there any additional command line output after starting the command? Does the error persist in version 2.0?

**Comment by suvi93** [comment]
there's no additional output. i have not tried with version 2.0. can i update 1.7 to 2.0? if so, how do i do it?

**Comment by schrins** [comment]
Whatshap v2.0 can be installed via conda or pip.

It's strange that there is no command line output. What happens if you just type `whatshap phase` without any parameters? Same with some dummy command like `whatshap phase dummy.vcf dummy.bam --no-reference` (I intentionally chose non-existing file names to see whether the program itself starts and realizes that the files do not exist).

How large are the input files that you tested?

**Comment by suvi93** [comment]
The options do get listed out when i just type `whatshap phase`. 
the input vcf is around 20GB and the bam file is around 45GB.

**Comment by schrins** [comment]
Ah, I overlooked that you got "working on chromosome 1". I thought you actually got no output at all and therefore I was checking for a broken installation. In the meantime I checked a 13GB VCF myself and it took 7 minutes for the tool to realize that the VCF is polyploid and contains no phasable variants. But you already were past this point.

Did you get any information about the number of found (and kept) reads or the number of phasing blocks? Or can you maybe post the exact command line output you get, when you run the tool? I want to see, whether the tool is stuck in some setup step or in the actual phasing algorithm, which can indeed run for several hours, even for a single chromosome.

**Comment by suvi93** [comment]
Hey Sven,

so yes after about 24 hrs I did get the information about the number of phasing blocks etc, It looks like the sample name in the VCF and the BAM did not match as it did find thousands of useable sites for phasing but did not actually phase any as the sample info did not match. the VCF header had the sample name as unknown and it said unknown not found in the BAM file.

I did go through the user guide again regarding the metadata part. so right now I'm using the `--ignore-read-groups` flag so that it can actually phase the variants. 

would I need to change anything else? in case this does not work should I change the sample name in the VCF header to match the sample name or read group in the BAM file?

**Comment by schrins** [comment]
The `--ignore-read-groups` flag should be sufficient, if your VCF and BAM only contain one sample. Otherwise Whatshap will complain about ambiguity in the samples to phase. It is odd, though, that your VCF takes so much longer to process. There is no obvious reason for me, at least.

**Comment by suvi93** [comment]
it finally worked, I got it to run a bit faster by including the `--chromosome` option. I work with a very large genome so it takes time to read through the files, nothing wrong with the tool, just that my files are very big.
Thanks for your help, you can go ahead and close the issue.
