### ISSUE TITLE
Whatshap haplotag

### ISSUE THREAD

**Issue by bsb2014** [whatshap/whatshap#475]
Hi there

1. I understand that phasing requires a read (or a pair of short reads) spanning two variants. I am wondering how many phased variants in a read are required for haplotag? If a read has only one phased variant, will the read be tagged? 

2. Whatshap phase can accept multiple bam files. Can whatshap haplotag accept multiple bam files?

3. As for pair end reads, if only one read of a pair spans the phased variants, will haplotag tag its mate read too? Thanks

**Comment by tobiasmarschall** [comment]
Haplotag takes a phased VCF as input and determines for each read whether it fits better to H1 or H2 as given in the VCF. To answer your questions:

1. Yes, a read spanning only one variant can be haplotagged.
2. Unlike phasing, haplotagging processes reads one at a time. So it does not make a difference whether multiple BAMs are processed one after each other or in with one command. From the top of my head haplotag does not support multiple BAMs, which is not a limitation for this reason.
3. It should. Please report back in case you should observe a different behavior.

(Closing this issue for now, feel free to reopen if you see the need.)

**Comment by bsb2014** [comment]
Thanks for your prompt response. 

If I use the same phased vcf (only one phased block) to tag two bam files, will the reads tagged with "H1" from both bam files are the same haplotype?
