### ISSUE TITLE
multithreading 'whatshap phase' on multi-VCF data

### ISSUE THREAD

**Issue by splaisan** [whatshap/whatshap#478]
Dear All,

I want to phase a multi-VCF obtained from GLnexus merging of 20 deepvariant mammalian samples (7GB gz file).

I do not find the argument --threads for the phase workflow and from the run so far it appears that I am running phase on a single core and that the process will take days!!

I am trying to use the --chromosome to palliate to this and run one chromosome per thread from the large multi-VCF file (7GB gz)
So far it seems to work but the phased VCF output also contains all other chromosome calls (unphased) which means I will duplicate <chr-nbr-times> the 7GB output instead of generating only single chr phased VCF outputs.

Is there a way, besides piping the output to some grep command, to parallelise the phase process and speed it up for a large multi-VCF file?

Also, I give now the 20+ BAM mapping files to the command while only the single chromosome mappings part of each are required. Is this leading to time waste as well and should I generate BAM subsets for each parallel job (which will duplicate my BAM footprint of >1TB!!)?

Thanks for any suggestion to make this phasing more time and resource efficient.

**Comment by splaisan** [comment]
Thanks a lot Sven, this is really helpful

I noticed when providing the full VCF as input that the input part not matching the --chromosome was written through unchanged, this lead to 19/20 of my 20 chromosomes without computed phasing data and only one with. 
This is why I split the VCF to single chromosome VCFs and handled them in parallel (with 20 samples represented)

Now from what you wrote, I could also split my multi-sample into 20 single sample VCF using and keep using --chromosome in // jobs with 20x lighter VCF subsets loaded in the python objects.

Am I right to believe that I could then run systematic combinations of chr x smpl to maybe 60 // jobs at a given time (now 20)?

If this does not use more RAM thanks to the current run, I may speed up the process a bit and release some RAM for other tasks.

I give it a try, not much to loose now ;-)

Thanks a lot, your help was very appreciated

**Comment by schrins** [comment]
Closing this for now, as I assume the issues are resolved or no longer of interest. If there is more to discuss, feel free to re-open.
