### ISSUE TITLE
Whatshap stats: NG50 is null for a group of samples and gt 4kb for another group, all other metrics are similar

### ISSUE THREAD

**Issue by splaisan** [whatshap/whatshap#486]
conda env with:
Python 3.10.13
whatshap 2.0

I analyzed the main chromosomes only out of my full reference genome phased variants using whatshap stats (excluding 1000 chrUn entities).

```
whatshap stats \
  --tsv="${mergedvcf%.vcf.gz}_${smpl}_main_stats.tsv" \
  --gtf="${mergedvcf%.vcf.gz}_${smpl}_main_stats.gtf" \
  --sample "${smpl}" \
  --chromosome "${chrlist}" \
  "${mergedvcf}" >"${mergedvcf%.vcf.gz}_stdout_${smpl}_stats.txt" 2>>"${outfolder}/${logpfx}"
```

The commands ran OK in parallel for each included sample (20). Nothing weird in the error log file.

I however get a weird NG50 result with all samples of group#2 returning NG50=0 (shown below) while the 10 other samples have a nice value for NG50 (4 of the 10 shown on top in the multiQC table below)

here is chr3 randomly picked from a group#2 sample returning NG50=0

```
---------------- Chromosome chr3 ----------------
      Variants in VCF:  4007883
         Heterozygous:   576128    (  505460    SNVs)
               Phased:   513971    (  469555    SNVs)
  Heterozygous phased:       89.2% (      92.9% SNVs)
             Unphased:    62133    (not considered below)
           Singletons:       24    (not considered below)
               Blocks:    22670

Block sizes (no. of variants)
         Sum of sizes:   513971    variants
    Median block size:        7.00 variants
   Average block size:       22.67 variants
        Largest block:     1516    variants
       Smallest block:        2    variants

Block lengths (basepairs)
       Sum of lengths: 85781172    bp
  Median block length:     1502.00 bp
 Average block length:     3764.81 bp
        Longest block:   101297    bp
       Shortest block:        1    bp
           Block NG50:        0    bp
```

and here is the same chr3 from a group#1 sample

```
---------------- Chromosome chr3 ----------------
      Variants in VCF:   4007883
         Heterozygous:    743331    (   658477    SNVs)
               Phased:    686156    (   626649    SNVs)
  Heterozygous phased:        92.3% (       95.2% SNVs)
             Unphased:     57156    (not considered below)
           Singletons:        19    (not considered below)
               Blocks:     22169

Block sizes (no. of variants)
         Sum of sizes:    686156    variants
    Median block size:        11.00 variants
   Average block size:        30.95 variants
        Largest block:      1809    variants
       Smallest block:         2    variants

Block lengths (basepairs)
       Sum of lengths: 121775517    bp
  Median block length:      2422.00 bp
 Average block length:      5468.39 bp
        Longest block:    127862    bp
       Shortest block:         1    bp
           Block NG50:      6121    bp
```

This is observed in the stdout of each of the group2 genome runs and appears also in the multiQC summary of which I show a screenshot below after masking the sample names (confidential)

If useful, I can provide original results only in private due to the presence of sample names.

Do you see a reason why the group2 samples computed 0 for NG50 while they refer to the same reference genome and were phased with similar commands in parallel jobs?

![Screenshot 2023-10-02 at 13 56 50](https://github.com/whatshap/whatshap/assets/858516/155d8fea-a96e-454b-8013-fe7d32ddcac8)

**Comment by pontushojer** [comment]
To compute NG50 values we need to know the length of the chromosome(s). This information can be provided through the `--chr-lengths` parameter, or from the VCF header if its present there. Could it be that only 4 of your samples have this information annotated in the header. There should have been an warning message for the remaining 6 samples, something like `VCF header does not contain contig lengths, cannot compute NG50. Consider using --chr-lengths`.

To make sure you produce this information you should provide a separate file i.e. use the `--chr-lengths` parameter.

**Comment by splaisan** [comment]
HI @pontushojer,
Weird!
All 20 jobs were run from the same command above and replacing the sample name and chromosome_list (identical for all) 
It is weird since all parallel jobs have the save VCF as input and all genomes where mapped in parallel with the same command.
I have no error in the log except a chr duplicate variant on chr1 for all samples
I will run a new batch command with --chr-lengths and the corresponsing csv list to be sure but suspect there is something else working here
I keep you updated here, thanks for the quick response

**Comment by pontushojer** [comment]
Now that I thought about this a bit longer I think I know what the actual issue is. 

The reason that NG50 is 0 in the first place is that the total phased length is 85,781,172 or about 85 Mb. The full length of chr3 is 198 Mb and inorder to get a NG50 value above 0 you need to cover at least half of that i.e. 198 / 2 = 99 Mb. In the sample that has a NG50 of 6121 the total phased length is about 121 Mb so that is why you get a value here. So the values given here are actually correct. 

If `whatshap stats` is unable to compute the NG50 it would instead be listed as `nan` not 0. In addition you would see something like the warning message I mentioned above.

**Comment by splaisan** [comment]
You did spot it Pontus, it is even in the doc (always read the doc! they keep saying...).

```
block_n50
The NG50 value of the distribution of the block lengths.

Note that this is an “NG50” (not “N50”), that is, the threshold of 50% is relative to the true length of the contig as reported in the VCF header. (For an N50, the length would be the sum of the length of all blocks). It is thus possible that the sum of all block lengths does not reach 50% of the length of the contig. In this case, the value in this column is set to 0.

```

So I can conclude that my run succeeded and that the lower coverage for these samples is responsible for the discrepancy.

Thanks for your kind help
