### ISSUE TITLE
Which variants are selected for whatshap compare?

### ISSUE THREAD

**Issue by TimD1** [whatshap/whatshap#488]
According to the documentation,

> _whatshap compare_ only looks at identical variants when it compares two files

I have a dataset that is correctly globally phased. WhatsHap reports a Hamming distance of 41, which means that there should be 41 identical variants with mismatched GTs. However, when I filter the original VCFs for heterozygous variants with identical (CHR, POS, REF, ALT) fields and mismatched GTs, I end up with 85.

Is there some form of additional filtering or variant grouping that WhatsHap performs? For example, is this only done for SNPs, or are nearby variants somehow clustered together?

Thanks,
Tim

**Comment by TimD1** [comment]
It looks like the `--switch-error-bed` option is useful for determining where the switch errors have occurred, but it would still be nice to know which variants are used in the calculation, if possible.

**Comment by tobiasmarschall** [comment]
Hi Tim,

it's a bit more involved than counting the number of mismatched GTs. Even if all HETs are in the same phased block then it is still possible that swapping the two haplotypes (which are in arbitrary order in a VCF) gives a smaller Hamming distance. So after replacing all `0|1` by `1|0` and vice versa the number if mismatches could be 41. But if there are multiple phased blocks than this is done for all blocks separately. Hope that explains your observation. Feel free to reopen in case it does not.

Tobias
