### ISSUE TITLE
Whatshap haplotag discards unaligned reads?

### ISSUE THREAD

**Issue by wac** [whatshap/whatshap#505]
Would it be possible to have an option to keep unaligned reads when using whatshap haplotag - it appears that unaligned reads are currently discarded.  

In practical use case this is so that the haplotagged bam alone would have all the sequencing reads needed for reanalysis (e.g. realignment)

**Comment by marcelm** [comment]
After checking the code, let me clarify: The intention is that `whatshap haplotag` outputs all input reads. `haplotag` has some code to copy over unmapped reads from the input to the output file. If this does not work, it would be great if you could provide an example where this happens using the most recent WhatsHap version.

Note that unmapped reads are not output when the `--region` command-line argument is used.

**Comment by wac** [comment]
My bad,  this is a very late followup to the issue reported here - I'm glad they ended up reporting it before I remembered to ha and glad to hear the fix is in!  I traced our issue to using the same whatshap version indicated in the bug report (so before the fix was introduced in v 1.6) - thanks for the prompt followup and sorry for the confusion

https://github.com/whatshap/whatshap/issues/397
