### ISSUE TITLE
Are the phase sets connected?

### ISSUE THREAD

**Issue by anuravi1234** [whatshap/whatshap#514]
Maybe this is a logical thing and I have not yet wrapped my head around all the features. 

I did phasing of a complex region in the human genome.  I then also ran "haplotag" to add the HP tag to the reads. this is to visualise them on IGV. I have two phase sets that are 100,000 bp apart. Is the haplotypes suggested within these phase sets connected? 

As in, the haplotypes suggested in one phase set also run true for the other phase set or are they independent?

**Comment by marcelm** [comment]
Closing this now, please let us know if you have further questions.
