### ISSUE TITLE
Supporting supplementary alignment

### ISSUE THREAD

**Issue by tobiasmarschall** [whatshap/whatshap#516]
Opening this issue to follow up on a conversation on supplementary alignments we just had with @nkkarpov @marcelm @snurk. This supersedes this historic issue, which actually has some useful thoughts and background information:
https://github.com/whatshap/whatshap/issues/23

**Comment by tobiasmarschall** [comment]
Here are some first pointers: 

- The main logic to create a read set is in https://github.com/whatshap/whatshap/blob/main/whatshap/variants.py and specifically here, which is the function creating a read set: https://github.com/whatshap/whatshap/blob/cefdaececfbb1aa63176da301a0c13ff368aceb4/whatshap/variants.py#L132
- Each read is turned into a `Read` object here: https://github.com/whatshap/whatshap/blob/cefdaececfbb1aa63176da301a0c13ff368aceb4/whatshap/variants.py#L216
- I didn't check in detail, but the way paired end reads are handled might serve as a template for how to combine multiple supplementary alignments into one `Read` object, see https://github.com/whatshap/whatshap/blob/cefdaececfbb1aa63176da301a0c13ff368aceb4/whatshap/variants.py#L159

**Comment by tobiasmarschall** [comment]
I don't have time to dig deeper today, but please feel free to ping us with questions.

**Comment by fenderglass** [comment]
Subscribing to this! Would be super helpful for SV analysis. Are you talking about using supplementary alignments to phase variants, or haplotag supplementary alignments (independently from primary) in `whatshap haplotag`? Both are needed, and the latter is especially pressing :)

**Comment by tobiasmarschall** [comment]
@fenderglass This issue was mostly about using supplementary alignments for phasing. But I'm curious: What would be a use case where you want to tag supplementary alignments independent from the primary ones? This might actually be relatively straighforward to add, but at least I never realized it was needed.

**Comment by fenderglass** [comment]
@tobiasmarschall it is mostly relevant for rearrangements that connect two distant loci in one or two different chromosomes. Here are a few scenarioes, that ultimately lead to a situation when split alignments from the same read should be in different phases. Those mostly occur in cancer, but may also cause genetic disorders in germline. 

1. A distant jump within one chromosome; start and end coordinates of the jump are in to different phase blocks. Those blocks may have H1/H2 switched relative to each other. 
2. Even if there is full-chromosome phasing and everything is one phase block, it is possible that a rearrangement may connect two different germline haplotypes.
3. Finally, you may have interchromosomal connection, which could be between pat/mat haplotypes.

If this is something that could be easily added, it would be a huge help!

**Comment by tobiasmarschall** [comment]
Ok, got it. That makes sense.

**Comment by nkkarpov** [comment]
@tobiasmarschall @marcelm I have prepared the PR with supplementary alignment support. Please take a look whenever you have time.

**Comment by tobiasmarschall** [comment]
@nkkarpov Awesome, thanks! Could you possibly add a test case? There are examples in [tests/test_run_phase.py](https://github.com/whatshap/whatshap/blob/main/tests/test_run_phase.py) and you could add another one with supplementary alignments to the same file.

@samarendra-pani Given that you recently phased a lot of ONT data sets, could you maybe test this new feature (when you have the time)?

**Comment by samarendra-pani** [comment]
Yes. I can do that in a week or two when I have some more time on my hands.

**Comment by eesiribloom** [comment]
@mikolmogorov based on the scenarios you mentioned would you recommend phasing with SAs and haplotagging supplementary alignments in cancer genomes even if `whatshap haplotag --tag-supplementary` can only assign SA to the same haplotype as primary alignments? And I'm not sure how it could do anything but this e.g. how could you phase your third scenario correctly?

**Comment by mikolmogorov** [comment]
@eesiribloom there is a pull request that addresses this, hopefully it will be merged soon: https://github.com/whatshap/whatshap/pull/546

**Comment by lkhilton** [comment]
The changes implemented in #546 would be incredibly useful - looking now at examples of tumour genomes where the supplementary alignment is incorrectly phased because it has inherited the haplotype tag from its primary alignment. Thanks for implementing this @mikolmogorov, can't wait to use it.
