### ISSUE TITLE
Question about whatshap stats

### ISSUE THREAD

**Issue by SanVerb** [whatshap/whatshap#525]
Hello 

I just have a small question on the whatshap stats result; specifically the shown number of variants ('Variants in the VCF: ...).

Whatshap stats shows the number of total variants in a phased vcf.

However, I noticed that this number is less than the actual variants in the vcf.

Which variants are excluded? I did some own calculations and I think multi allelic variants are excluded, but I feel like there might be additional criteria?

I did try to look at the source code, but that is still a bit advanced for me as I'm still very new to the world of bioinformatics.

Kind Regards

Sanché Verbeeck

**Comment by marcelm** [comment]
Hi, please see the [documentation for `whatshap stats`](https://whatshap.readthedocs.io/en/latest/guide.html#the-tsv-statistics-format). The section this link goes to is about the TSV format, but the numbers are the same. The number you mean should be the one that is shown in the *variants* column, which has this explanation:
> Number of biallelic variants in the input VCF, but excluding any non-SNV variants if `--only-snvs` was used.

**Comment by SanVerb** [comment]
Hello, thank you for the quick respons. 

Could it be that besides excluding multi allelic variants (so only including biallelic as the documentations says), duplicates are also removed although this is not mentioned in the documentation?
I calculated the biallelic variants in my phased vcf, but never got the same number as whatshap stats, untill I also took duplicate positions into account.

Extra note, slightly outside of this topic: My phased vcf has actually multiple duplicate positions that seem to be ignored (concluded from my own calculations and comparing with the mentioned variants by whatshap stats), however I noticed that only one such positions is mentioned in the phasing logs.

Kind regards

Sanché verbeeck

**Comment by marcelm** [comment]
Yes, you’re right, this was missing from the documentation. I have added this now. You should even have gotten a "Skipping duplicated position ... on chromosome ..." warning, did you see any?

**Comment by SanVerb** [comment]
Hello

I checked my log files and yes: I did get that message so that looks fine!

Thank you!

Sanché Verbeeck

**Comment by marcelm** [comment]
Alright, is it ok to close this then?

**Comment by SanVerb** [comment]
Hello

Yes, this may be closed! Thank you for the help!!


Kind regards

Sanché Verbeeck
