### ISSUE TITLE
pedigree relationship was ignored

### ISSUE THREAD

**Issue by leon945945** [whatshap/whatshap#530]
- WhatsHap version 1.7 and Python version 3.9.17
- conda install WhatsHap
- whatshap phase --ped ped.txt --reference=reference  --sample sample --indels -o sample.phased.vcf sample.vcf maternal.bam progeny.TJH.bam paternal.TJH.bam

Hi, I used `whatshap` to phase variants with pedigree information, but whatshap thraw an warning: 
> Relationship progeny/maternal/paternal ignored because at least one of the individuals was not given by --samples.

As you can see, I have provided the `--sample` parameter, and `whatshap` didn't perform predigree-based variants phase.

Please give me some suggestions, thanks very much.

**Comment by tobiasmarschall** [comment]
From you command-line it looks like you provided one sample. You should provide all the samples part of the pedigree you want to phase.

**Comment by leon945945** [comment]
Thanks, I cancelled the `--sample` parameter, the warning was disappeared.
