### ISSUE TITLE
OSError while trying to haplotag 

### ISSUE THREAD

**Issue by eaooms** [whatshap/whatshap#537]
- WhatsHap and Python version (`python -V` and `whatshap --version`) 
WhatsHap version 2.3 and Python 3.9

- How you installed the tool (conda, pip)
Installed with pip3 install --user whatshap

- Which command-line parameters you used
whatshap haplotag -o haplo_phased.bam --ignore-read-groups \
--reference GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
phased_data.vcf.gz WesData.cram

  [E::cram_read_container] Container header CRC32 failure
  Traceback (most recent call last):
    File "/home/eooms/.local/bin/whatshap", line 8, in <module>
      sys.exit(main())
    File "/home/eooms/.local/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
      module.main(args)
    File "/home/eooms/.local/lib/python3.9/site-packages/whatshap/cli/haplotag.py", line 684, in main
      run_haplotag(**vars(args))
    File "/home/eooms/.local/lib/python3.9/site-packages/whatshap/cli/haplotag.py", line 666, in run_haplotag
      for alignment in bam_reader.fetch(until_eof=True):
    File "pysam/libcalignmentfile.pyx", line 2212, in pysam.libcalignmentfile.IteratorRowAll.__next__
  OSError: truncated file

My phased_data.vcf i got via the whatshap phase command.

I have 3 samples of data and with 2 of the samples the whatshap haplotag function works but with this sample i got the OSError

**Comment by marcelm** [comment]
The problem appears to be in the CRAM file. Can you please run `samtools view -c WesData.cram`? (You may need to provide the reference sequence with `-T`: `samtools view -c -T GCA_000001405.15_GRCh38_no_alt_analysis_set.fna WesData.cram`.

`samtools view -c` just prints the number of records in the CRAM file. If that command fails with a similar message to the one `whatshap haplotag` outputs (regarding a "container header CR32 failure" or so), then the CRAM file is broken, so then it would not be an issue in WhatsHap.

**Comment by eaooms** [comment]
Dear Marcelm,

I ran the command and it gave me a number of records, not an error.

**Comment by marcelm** [comment]
Can you perhaps provide me with the input files so that I can attempt to reproduce the problem myself? (If you want to send an e-mail, you can find my address in my profile.)

**Comment by eaooms** [comment]
Dear Marcelm, 
unfortunately it is not possible to share my data as I am working with patient data, are there any steps I can perform myself to test something

**Comment by marcelm** [comment]
Ok, a couple of things you can do.

* I assume you already did this: Re-run `whatshap haplotag`. Do you get the same error?
* Run `samtools view -h WesData.cram > /dev/null` (note: no `-c`). Does it give an error?
* Re-create the index: `samtools index WesData.cram`. Does that give you an error? If not, try re-running haplotag.
* Put this code into a file named `count.py`:
```python
import sys
from pysam import AlignmentFile

with AlignmentFile(sys.argv[1], reference_filename=sys.argv[2] if len(sys.argv) > 2 else None) as af:
    n = 0
    for record in af.fetch(until_eof=True):
        n += 1
    print(n)
```
Then run `python3 count.py WesData.cram`. What is the output?

Then run `python3 count.py WesData.cram GCA_000001405.15_GRCh38_no_alt_analysis_set.fna`. What is the output?

**Comment by eaooms** [comment]
I did these 3 things: 

I assume you already did this: Re-run whatshap haplotag. Do you get the same error?
Yes i get the same error 

Run samtools view -h WesData.cram > /dev/null (note: no -c). Does it give an error?
No it does not 

Re-create the index: samtools index WesData.cram. Does that give you an error? If not, try re-running haplotag.
I made a new index file and try re-running. 
I got the same error. 

This is my error file to give you more of an example: 

Found 1 sample(s) in input VCF
Found 1 sample(s) in BAM file
Number of supplementary alignments: 0
Number of non-singleton groups: 49254
Skipped 0 groups
Found 201919 reads covering 6708 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 35051
Skipped 0 groups
Found 145813 reads covering 4715 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 26483
Skipped 0 groups
Found 109982 reads covering 3616 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 21860
Skipped 0 groups
Found 90710 reads covering 3068 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 26822
Skipped 0 groups
Found 109132 reads covering 3418 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 29811
Skipped 0 groups
Found 109616 reads covering 4092 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 28813
Skipped 0 groups
Found 107055 reads covering 3668 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 16543
Skipped 0 groups
Found 69421 reads covering 2632 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 19308
Skipped 0 groups
Found 77427 reads covering 2723 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 21701
Skipped 0 groups
Found 85206 reads covering 3156 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 33105
Skipped 0 groups
Found 124411 reads covering 3778 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 34173
Skipped 0 groups
Found 133023 reads covering 3657 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 9088
Skipped 0 groups
Found 36567 reads covering 1423 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 18692
Skipped 0 groups
Found 76143 reads covering 2162 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 18111
Skipped 0 groups
Found 75206 reads covering 2641 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 21501
Skipped 0 groups
Found 85566 reads covering 2864 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 29217
Skipped 0 groups
Found 114453 reads covering 3775 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 9360
Skipped 0 groups
Found 40793 reads covering 1363 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 41655
Skipped 0 groups
Found 155969 reads covering 4768 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 13472
Skipped 0 groups
Found 50758 reads covering 1783 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 7761
Skipped 0 groups
Found 29910 reads covering 1175 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 12221
Skipped 0 groups
Found 46913 reads covering 1728 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 1446
Skipped 0 groups
Found 4757 reads covering 138 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 69
Skipped 0 groups
Found 286 reads covering 55 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 19
Skipped 0 groups
Found 107 reads covering 4 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
Number of supplementary alignments: 0
Number of non-singleton groups: 0
Skipped 0 groups
Found 0 reads covering 0 variants
[E::cram_read_container] Container header CRC32 failure
Traceback (most recent call last):
  File "/home/umcg-eooms/.local/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/home/eooms/.local/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/eooms/.local/lib/python3.9/site-packages/whatshap/cli/haplotag.py", line 684, in main
    run_haplotag(**vars(args))
  File "/home/eooms/.local/lib/python3.9/site-packages/whatshap/cli/haplotag.py", line 666, in run_haplotag
    for alignment in bam_reader.fetch(until_eof=True):
  File "pysam/libcalignmentfile.pyx", line 2212, in pysam.libcalignmentfile.IteratorRowAll.__next__
OSError: truncated file

**Comment by eaooms** [comment]
Then run python3 count.py WesData.cram. What is the output?
Output = 
This may become large; see the samtools(1) manual page REF_CACHE discussion
[E::cram_populate_ref] Creating reference at /home/eooms/.cache/hts-ref/cc/04/4cc2256a1141212660fb07b6171e failed: Disk quota exceeded

Then run python3 count.py WesData.cram GCA_000001405.15_GRCh38_no_alt_analysis_set.fna. What is the output?
output = 73472298

**Comment by marcelm** [comment]
I may have found the problem.

Can you please edit file `/home/eooms/.local/lib/python3.9/site-packages/whatshap/cli/haplotag.py"`. In line 666, change this line:
```
            for alignment in bam_reader.fetch(until_eof=True):
```
to this:
```
            for alignment in bam_reader.fetch(contig="*"):
```
And re-try?

**Comment by marcelm** [comment]
Great, thanks for reporting! This is now fixed in WhatsHap.
