### ISSUE TITLE
Pedigree phasing a trio/duo with sequencing data on only the child

### ISSUE THREAD

**Issue by DNA-Dave** [whatshap/whatshap#540]
Hello,

I have some vcfs called from short read WGS data on trios (mother, father, and child) or duos (either mother or father and child) with long read RNA seq data that I would like to phase with whatshap. Therefore, I believe that the pedigree phasing module would be good for my case. However, I only have long read RNA sequencing data on the child, and I do not have any such data for one or both of the parents. Does whatshap support this mode of operation? It is not entirely clear in the documentation.

Many thanks.

**Comment by tobiasmarschall** [comment]
There is no duo mode right now, unfortunately. As for mixing RNA and DNA data, I think that should work, i.e. if you provide long read transcriptome data for the child, it should help the phasing. Alternatively, you could phase just from the trio (plus short-read) data and use the resulting phased VCF to haplotag the RNA reads.

**Comment by DNA-Dave** [comment]
Thank you--one more question. Is it possible to run pedigree phasing using just the RNA-seq reads? Or does it require bams for all three individuals in the trio?

**Comment by tobiasmarschall** [comment]
It's perfectly fine to only use the RNA-seq of the child. In this case, these reads will be phased using the genotype information of the parents in the VCF.
