### ISSUE TITLE
Recommend parameter for R10.4 ONT phasing

### ISSUE THREAD

**Issue by JMencius** [whatshap/whatshap#547]
Hi developers of Whatshap, 
  I wonder if there is a recommend parameter for R10 Q20 ONT data, since whatshap can set `--error-rate` and `--maximum-error-rate` manually and the preset parameters are relatively conservative for R10 Q20 ONT data.

**Comment by tobiasmarschall** [comment]
These parameters pertain only to read merging. I would recommend to just use default settings. Especially low-error long read data should work very well out of the box. I'm closing this for now, but please don't hesitate to re-open in case you observe any unexpected behavior.

**Comment by JMencius** [comment]
Many thanks.
