### ISSUE TITLE
SNV profile for phasing long read WGS

### ISSUE THREAD

**Issue by ywzhang071394** [whatshap/whatshap#556]
Hi,

We now have both short-read and Pacbio-Hifi WGS data with similar sequencing depth (30~40x) and we used deepvariant to call SNVs for them.
High-quality short-read SNVs were recommended by the WhatShap document to phase long-read data.
I was just curious about, in this case, is short-read still more accurate than Pacbio-HiFi? 
Are there anyway to compare the phasing results?

Thanks

**Comment by ywzhang071394** [comment]
The phased_snvs_fraction of short read SNVs is 83% (total SNV: 6,866,678) while that of long read is 65% (total SNV: 10,180,691). Cuz we do not have the truth from trio data, I wonder if we can use the summary of Whatshap stats to roughly compare the phasing efficiency between using longread SNVs and shortread SNVs.

**Comment by tobiasmarschall** [comment]
30-40x Hifi data should give you excellent SNV calls. In fact you could also run assemblies (e.g. using HifiAsm) from this coverage. If you are curious you could just compare the SNV calls between the platform and their genotypes. Or take the intersection of HET sites if you want to be extra strict. The phasing should be done from the Hifi reads. Closing for now, feel free to reopen in case of more questions.
