### ISSUE TITLE
phasing 300 inds with incomplete pedigree

### ISSUE THREAD

**Issue by robbaci** [whatshap/whatshap#560]
Hi All
I have a population of 500 diploid individuals (Illumina sequences >15x) with varying degree of relationship, from full-sib to unparented. 
Is it possible to phase so many individuals, using and incomplete .ped file (some inds have no relationship so, mother father 0 0) ? 

I also worry specifically about the capacity for the software to accept some 500 bam files.

Or would it be better to first phase only the related ones, and then using this as a reference population (in another software if WhatsHap doesnt not deal with a ref pop) ?

Thanks a lot for your advice !

**Comment by tobiasmarschall** [comment]
This sounds a use case whatshap (alone) is not designed for. You will need to use a population phasing tool and if I remember correctly e.g. Shapeit has a way to input phase information from reads by reading whatshap input. I cannot give you detailed help as I have never done this myself, but hope that this pointer is helpful.

**Comment by robbaci** [comment]
Thank you Tobias, your pointer is useful indeed. There is a read-based phasing tool in ShapeIt (extractPIRs) so one may be tempted to do everything within ShapeIt, but it was published in 2013 and not update since, so I was wondering if whatsHap provided some more efficient read-based phasing ? If yes, it will certainly motivate to combine the two tools (which raise the question of making the output of whatsHap compatible with the requirement of ShapeIt). 
Ok thank you, I will appreciate any further help, and I will keep you update if I can succesfully progress.
