### ISSUE TITLE
how does whatshap recognize heterozygous SNP?

### ISSUE THREAD

**Issue by charliechen912ilovbash** [whatshap/whatshap#565]
I have a vcf file without `AF` in the `INFO` column. 
Instead, there is a `MLEAF` in the `INFO` column, with the description: "Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed".
The `whatshap phasing` and `whatshap haplotag` seem to perform well.
So I am wondering that how does whatshap recognize heterozygous SNP for phasing.

**Comment by charliechen912ilovbash** [comment]
I see, thanks!!!!

**Comment by schrins** [comment]
To my knowledge, the `AF` field is not used.

**Comment by charliechen912ilovbash** [comment]
I understood, thanks !
