### ISSUE TITLE
Inconsistent non-singleton blocks between whatshap compare and whatshap stats

### ISSUE THREAD

**Issue by JMencius** [whatshap/whatshap#567]
Hi developers, I got inconsistent non-singleton blocks between `whatshap compare` and `whatshap stats`, following is the detail output both for `chr1` in the query vcf file (whatshap produced)
in `whatshap compare` the number is `886`
```
---------------- Chromosome chr1 ----------------
VARIANT COUNTS (heterozygous / all): 
           whatshap:    200262 /    328022
              truth:    164159 /    271525
              UNION:    200711 /    328450
       INTERSECTION:    163710 /    271097
PAIRWISE COMPARISON: whatshap <--> truth:
         common heterozygous variants:    163710
         (restricting to these below)
        non-singleton blocks in whatshap:       886 
                 --> covered variants:    163390
        non-singleton blocks in truth:        21
                 --> covered variants:    163092
    non-singleton intersection blocks:       890
                 --> covered variants:    162805
```
But in `whatshap stats` the number is `978`
```
---------------- Chromosome chr1 ----------------
      Variants in VCF:    327879
         Heterozygous:    200119    (   200119    SNVs)
               Phased:    195321    (   195321    SNVs)
  Heterozygous phased:        97.6% (       97.6% SNVs)
             Unphased:      4707    (not considered below)
           Singletons:        91    (not considered below)
           Blocks:       978 
```
I am confused and looking forward for your help.

**Comment by JMencius** [comment]
I manually check the linecount of the `tsv` output of `whatshap` stats, total block of `chr1` is 1069 (= 91 (singletons) + 978 (non-singleton)), I think the output of `whatshap stats` is correct

**Comment by schrins** [comment]
I think the confusion regarding the block count could arise from the way `whatshap compare` works: Everything that is listed below `PAIRWISE COMPARISON` is only based on variants that present in both the phased output and the provided ground truth. We can see from above that the phasing output has about 25% more heterozygous variants than both the ground truth and intersection of both. This means that entire phasing blocks could missing in the intersection if they are relatively small or if there are larger regions missing in the ground truth file. This would explain why the number of non-singletons is smaller in `whatshap compare`.

However, the total number of variants in the input is slightly different between `stats` and `compare`. I don't know why that is.

**Comment by JMencius** [comment]
@schrins Vielen Dank.
