### ISSUE TITLE
How does split work when more than 1 variant on the read?

### ISSUE THREAD

**Issue by CWYuan08** [whatshap/whatshap#573]
Hi, thank you very much for the tool,
I am trying to measure allelic expression with nanopore data. I have a phased vcf of heterozygous snps, if there are more than 1 variant on the read, how does split work exactly? 
Many thanks!

Best,
CW

**Comment by tobiasmarschall** [comment]
If I understand the question correctly, then you might want to look at `whatshap haplotag`, which assigns an `HP` tag based on the het SNPs covered by that read. If there are multiple SNPs on one read, then `haplotag` would pick the haplotype to which the reads fits better. Does that answer your question?

**Comment by CWYuan08** [comment]
Dear @tobiasmarschall, thank you for prompt reply!
Yes, when there are for example two variants of different haplotypes on the same read, does haplotag discard the read?

**Comment by tobiasmarschall** [comment]
If it's an exact tie, then the read will not be tagged, i.e. it remains in the output BAM but without an `HP` tag. If there is a majority of alleles from one haplotype, then the read will be tagged accordingly.

**Comment by tobiasmarschall** [comment]
Closing this for now. Feel free to reopen in case you have more questions.
